//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACESSO.ADMINISTRATIVO.CParametro {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PARAMETRO", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class PARAMETRO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PACodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PAServidorCorreioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PAServidorDominioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PATempoExpiraSaidaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PACodigo {
            get {
                return this.PACodigoField;
            }
            set {
                if ((this.PACodigoField.Equals(value) != true)) {
                    this.PACodigoField = value;
                    this.RaisePropertyChanged("PACodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PAServidorCorreio {
            get {
                return this.PAServidorCorreioField;
            }
            set {
                if ((object.ReferenceEquals(this.PAServidorCorreioField, value) != true)) {
                    this.PAServidorCorreioField = value;
                    this.RaisePropertyChanged("PAServidorCorreio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PAServidorDominio {
            get {
                return this.PAServidorDominioField;
            }
            set {
                if ((object.ReferenceEquals(this.PAServidorDominioField, value) != true)) {
                    this.PAServidorDominioField = value;
                    this.RaisePropertyChanged("PAServidorDominio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PATempoExpiraSaida {
            get {
                return this.PATempoExpiraSaidaField;
            }
            set {
                if ((this.PATempoExpiraSaidaField.Equals(value) != true)) {
                    this.PATempoExpiraSaidaField = value;
                    this.RaisePropertyChanged("PATempoExpiraSaida");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CParametro.ICParametro")]
    public interface ICParametro {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICParametro/Alterar", ReplyAction="http://tempuri.org/ICParametro/AlterarResponse")]
        void Alterar(ACESSO.ADMINISTRATIVO.CParametro.PARAMETRO oParametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICParametro/SelecionarParametro", ReplyAction="http://tempuri.org/ICParametro/SelecionarParametroResponse")]
        ACESSO.ADMINISTRATIVO.CParametro.PARAMETRO SelecionarParametro();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICParametroChannel : ACESSO.ADMINISTRATIVO.CParametro.ICParametro, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CParametroClient : System.ServiceModel.ClientBase<ACESSO.ADMINISTRATIVO.CParametro.ICParametro>, ACESSO.ADMINISTRATIVO.CParametro.ICParametro {
        
        public CParametroClient() {
        }
        
        public CParametroClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CParametroClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CParametroClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CParametroClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Alterar(ACESSO.ADMINISTRATIVO.CParametro.PARAMETRO oParametro) {
            base.Channel.Alterar(oParametro);
        }
        
        public ACESSO.ADMINISTRATIVO.CParametro.PARAMETRO SelecionarParametro() {
            return base.Channel.SelecionarParametro();
        }
    }
}
