//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACESSO.ADMINISTRATIVO.CDigital {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DIGITAL", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class DIGITAL : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DiCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DiDataVencimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char DiDedoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char DiMaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DiCodigo {
            get {
                return this.DiCodigoField;
            }
            set {
                if ((this.DiCodigoField.Equals(value) != true)) {
                    this.DiCodigoField = value;
                    this.RaisePropertyChanged("DiCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DiDataVencimento {
            get {
                return this.DiDataVencimentoField;
            }
            set {
                if ((this.DiDataVencimentoField.Equals(value) != true)) {
                    this.DiDataVencimentoField = value;
                    this.RaisePropertyChanged("DiDataVencimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char DiDedo {
            get {
                return this.DiDedoField;
            }
            set {
                if ((this.DiDedoField.Equals(value) != true)) {
                    this.DiDedoField = value;
                    this.RaisePropertyChanged("DiDedo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char DiMao {
            get {
                return this.DiMaoField;
            }
            set {
                if ((this.DiMaoField.Equals(value) != true)) {
                    this.DiMaoField = value;
                    this.RaisePropertyChanged("DiMao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HASHDIGITAL", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class HASHDIGITAL : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HaCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HaCodigoDigitalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HaCodigoEquipamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HaCodigoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HaCredencialBiometricaTextualField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HaCodigo {
            get {
                return this.HaCodigoField;
            }
            set {
                if ((this.HaCodigoField.Equals(value) != true)) {
                    this.HaCodigoField = value;
                    this.RaisePropertyChanged("HaCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HaCodigoDigital {
            get {
                return this.HaCodigoDigitalField;
            }
            set {
                if ((this.HaCodigoDigitalField.Equals(value) != true)) {
                    this.HaCodigoDigitalField = value;
                    this.RaisePropertyChanged("HaCodigoDigital");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HaCodigoEquipamento {
            get {
                return this.HaCodigoEquipamentoField;
            }
            set {
                if ((this.HaCodigoEquipamentoField.Equals(value) != true)) {
                    this.HaCodigoEquipamentoField = value;
                    this.RaisePropertyChanged("HaCodigoEquipamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HaCodigoUsuario {
            get {
                return this.HaCodigoUsuarioField;
            }
            set {
                if ((this.HaCodigoUsuarioField.Equals(value) != true)) {
                    this.HaCodigoUsuarioField = value;
                    this.RaisePropertyChanged("HaCodigoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HaCredencialBiometricaTextual {
            get {
                return this.HaCredencialBiometricaTextualField;
            }
            set {
                if ((object.ReferenceEquals(this.HaCredencialBiometricaTextualField, value) != true)) {
                    this.HaCredencialBiometricaTextualField = value;
                    this.RaisePropertyChanged("HaCredencialBiometricaTextual");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CDigital.ICDigital")]
    public interface ICDigital {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDigital/Excluir", ReplyAction="http://tempuri.org/ICDigital/ExcluirResponse")]
        void Excluir(ACESSO.ADMINISTRATIVO.CDigital.DIGITAL oDig);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDigital/Incluir", ReplyAction="http://tempuri.org/ICDigital/IncluirResponse")]
        void Incluir(ACESSO.ADMINISTRATIVO.CDigital.DIGITAL Digital1, ACESSO.ADMINISTRATIVO.CDigital.HASHDIGITAL Hash1, ACESSO.ADMINISTRATIVO.CDigital.DIGITAL Digital2, ACESSO.ADMINISTRATIVO.CDigital.HASHDIGITAL Hash2, ACESSO.ADMINISTRATIVO.CDigital.DIGITAL Digital3, ACESSO.ADMINISTRATIVO.CDigital.HASHDIGITAL Hash3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICDigital/Digitais", ReplyAction="http://tempuri.org/ICDigital/DigitaisResponse")]
        ACESSO.ADMINISTRATIVO.CDigital.DIGITAL[] Digitais(int CodigoUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICDigitalChannel : ACESSO.ADMINISTRATIVO.CDigital.ICDigital, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CDigitalClient : System.ServiceModel.ClientBase<ACESSO.ADMINISTRATIVO.CDigital.ICDigital>, ACESSO.ADMINISTRATIVO.CDigital.ICDigital {
        
        public CDigitalClient() {
        }
        
        public CDigitalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CDigitalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CDigitalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CDigitalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Excluir(ACESSO.ADMINISTRATIVO.CDigital.DIGITAL oDig) {
            base.Channel.Excluir(oDig);
        }
        
        public void Incluir(ACESSO.ADMINISTRATIVO.CDigital.DIGITAL Digital1, ACESSO.ADMINISTRATIVO.CDigital.HASHDIGITAL Hash1, ACESSO.ADMINISTRATIVO.CDigital.DIGITAL Digital2, ACESSO.ADMINISTRATIVO.CDigital.HASHDIGITAL Hash2, ACESSO.ADMINISTRATIVO.CDigital.DIGITAL Digital3, ACESSO.ADMINISTRATIVO.CDigital.HASHDIGITAL Hash3) {
            base.Channel.Incluir(Digital1, Hash1, Digital2, Hash2, Digital3, Hash3);
        }
        
        public ACESSO.ADMINISTRATIVO.CDigital.DIGITAL[] Digitais(int CodigoUsuario) {
            return base.Channel.Digitais(CodigoUsuario);
        }
    }
}
