//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACESSO.PONTOCONTROLE.CPonto {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PONTOCONTROLE", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class PONTOCONTROLE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PoBiometriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PoCartaoRFIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PoCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PoControlaSaidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PoDescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PoDisparaAlarmeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PoNomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PoObservacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PoPermiteLiberacaoForcadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PoQtdMediaPessoasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PoQtdVerificaEquipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PoSenhaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PoSmartCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> PoTentativaIndevidaDisparaAlarmeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char PoTipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PoBiometria {
            get {
                return this.PoBiometriaField;
            }
            set {
                if ((this.PoBiometriaField.Equals(value) != true)) {
                    this.PoBiometriaField = value;
                    this.RaisePropertyChanged("PoBiometria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PoCartaoRFID {
            get {
                return this.PoCartaoRFIDField;
            }
            set {
                if ((this.PoCartaoRFIDField.Equals(value) != true)) {
                    this.PoCartaoRFIDField = value;
                    this.RaisePropertyChanged("PoCartaoRFID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PoCodigo {
            get {
                return this.PoCodigoField;
            }
            set {
                if ((this.PoCodigoField.Equals(value) != true)) {
                    this.PoCodigoField = value;
                    this.RaisePropertyChanged("PoCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PoControlaSaida {
            get {
                return this.PoControlaSaidaField;
            }
            set {
                if ((this.PoControlaSaidaField.Equals(value) != true)) {
                    this.PoControlaSaidaField = value;
                    this.RaisePropertyChanged("PoControlaSaida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PoDescricao {
            get {
                return this.PoDescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.PoDescricaoField, value) != true)) {
                    this.PoDescricaoField = value;
                    this.RaisePropertyChanged("PoDescricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PoDisparaAlarme {
            get {
                return this.PoDisparaAlarmeField;
            }
            set {
                if ((this.PoDisparaAlarmeField.Equals(value) != true)) {
                    this.PoDisparaAlarmeField = value;
                    this.RaisePropertyChanged("PoDisparaAlarme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PoNome {
            get {
                return this.PoNomeField;
            }
            set {
                if ((object.ReferenceEquals(this.PoNomeField, value) != true)) {
                    this.PoNomeField = value;
                    this.RaisePropertyChanged("PoNome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PoObservacao {
            get {
                return this.PoObservacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.PoObservacaoField, value) != true)) {
                    this.PoObservacaoField = value;
                    this.RaisePropertyChanged("PoObservacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PoPermiteLiberacaoForcada {
            get {
                return this.PoPermiteLiberacaoForcadaField;
            }
            set {
                if ((this.PoPermiteLiberacaoForcadaField.Equals(value) != true)) {
                    this.PoPermiteLiberacaoForcadaField = value;
                    this.RaisePropertyChanged("PoPermiteLiberacaoForcada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PoQtdMediaPessoas {
            get {
                return this.PoQtdMediaPessoasField;
            }
            set {
                if ((this.PoQtdMediaPessoasField.Equals(value) != true)) {
                    this.PoQtdMediaPessoasField = value;
                    this.RaisePropertyChanged("PoQtdMediaPessoas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PoQtdVerificaEquip {
            get {
                return this.PoQtdVerificaEquipField;
            }
            set {
                if ((this.PoQtdVerificaEquipField.Equals(value) != true)) {
                    this.PoQtdVerificaEquipField = value;
                    this.RaisePropertyChanged("PoQtdVerificaEquip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PoSenha {
            get {
                return this.PoSenhaField;
            }
            set {
                if ((this.PoSenhaField.Equals(value) != true)) {
                    this.PoSenhaField = value;
                    this.RaisePropertyChanged("PoSenha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PoSmartCard {
            get {
                return this.PoSmartCardField;
            }
            set {
                if ((this.PoSmartCardField.Equals(value) != true)) {
                    this.PoSmartCardField = value;
                    this.RaisePropertyChanged("PoSmartCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> PoTentativaIndevidaDisparaAlarme {
            get {
                return this.PoTentativaIndevidaDisparaAlarmeField;
            }
            set {
                if ((this.PoTentativaIndevidaDisparaAlarmeField.Equals(value) != true)) {
                    this.PoTentativaIndevidaDisparaAlarmeField = value;
                    this.RaisePropertyChanged("PoTentativaIndevidaDisparaAlarme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char PoTipo {
            get {
                return this.PoTipoField;
            }
            set {
                if ((this.PoTipoField.Equals(value) != true)) {
                    this.PoTipoField = value;
                    this.RaisePropertyChanged("PoTipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="USUARIO", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class USUARIO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> USAdministradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> USAuditorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool USBloqueadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int USCODIGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> USCODIGOESTAGIARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> USCODIGOTERCEIROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> USCODIGOVISITANTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> USGerenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> USMATFUNCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USMotivoBloqueioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> USSegurancaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USSenhaOpcionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char USTIPOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USUSUARIOREDEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> USAdministrador {
            get {
                return this.USAdministradorField;
            }
            set {
                if ((this.USAdministradorField.Equals(value) != true)) {
                    this.USAdministradorField = value;
                    this.RaisePropertyChanged("USAdministrador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> USAuditor {
            get {
                return this.USAuditorField;
            }
            set {
                if ((this.USAuditorField.Equals(value) != true)) {
                    this.USAuditorField = value;
                    this.RaisePropertyChanged("USAuditor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool USBloqueado {
            get {
                return this.USBloqueadoField;
            }
            set {
                if ((this.USBloqueadoField.Equals(value) != true)) {
                    this.USBloqueadoField = value;
                    this.RaisePropertyChanged("USBloqueado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int USCODIGO {
            get {
                return this.USCODIGOField;
            }
            set {
                if ((this.USCODIGOField.Equals(value) != true)) {
                    this.USCODIGOField = value;
                    this.RaisePropertyChanged("USCODIGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> USCODIGOESTAGIARIO {
            get {
                return this.USCODIGOESTAGIARIOField;
            }
            set {
                if ((this.USCODIGOESTAGIARIOField.Equals(value) != true)) {
                    this.USCODIGOESTAGIARIOField = value;
                    this.RaisePropertyChanged("USCODIGOESTAGIARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> USCODIGOTERCEIRO {
            get {
                return this.USCODIGOTERCEIROField;
            }
            set {
                if ((this.USCODIGOTERCEIROField.Equals(value) != true)) {
                    this.USCODIGOTERCEIROField = value;
                    this.RaisePropertyChanged("USCODIGOTERCEIRO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> USCODIGOVISITANTE {
            get {
                return this.USCODIGOVISITANTEField;
            }
            set {
                if ((this.USCODIGOVISITANTEField.Equals(value) != true)) {
                    this.USCODIGOVISITANTEField = value;
                    this.RaisePropertyChanged("USCODIGOVISITANTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> USGerente {
            get {
                return this.USGerenteField;
            }
            set {
                if ((this.USGerenteField.Equals(value) != true)) {
                    this.USGerenteField = value;
                    this.RaisePropertyChanged("USGerente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> USMATFUNC {
            get {
                return this.USMATFUNCField;
            }
            set {
                if ((this.USMATFUNCField.Equals(value) != true)) {
                    this.USMATFUNCField = value;
                    this.RaisePropertyChanged("USMATFUNC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USMotivoBloqueio {
            get {
                return this.USMotivoBloqueioField;
            }
            set {
                if ((object.ReferenceEquals(this.USMotivoBloqueioField, value) != true)) {
                    this.USMotivoBloqueioField = value;
                    this.RaisePropertyChanged("USMotivoBloqueio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> USSeguranca {
            get {
                return this.USSegurancaField;
            }
            set {
                if ((this.USSegurancaField.Equals(value) != true)) {
                    this.USSegurancaField = value;
                    this.RaisePropertyChanged("USSeguranca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USSenhaOpcional {
            get {
                return this.USSenhaOpcionalField;
            }
            set {
                if ((object.ReferenceEquals(this.USSenhaOpcionalField, value) != true)) {
                    this.USSenhaOpcionalField = value;
                    this.RaisePropertyChanged("USSenhaOpcional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char USTIPO {
            get {
                return this.USTIPOField;
            }
            set {
                if ((this.USTIPOField.Equals(value) != true)) {
                    this.USTIPOField = value;
                    this.RaisePropertyChanged("USTIPO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USUSUARIOREDE {
            get {
                return this.USUSUARIOREDEField;
            }
            set {
                if ((object.ReferenceEquals(this.USUSUARIOREDEField, value) != true)) {
                    this.USUSUARIOREDEField = value;
                    this.RaisePropertyChanged("USUSUARIOREDE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FUNCIONARIO", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class FUNCIONARIO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FUCodigoLocalidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FUCodigoLotacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FUMATFUNCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FUNOMFUNCField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FUCodigoLocalidade {
            get {
                return this.FUCodigoLocalidadeField;
            }
            set {
                if ((this.FUCodigoLocalidadeField.Equals(value) != true)) {
                    this.FUCodigoLocalidadeField = value;
                    this.RaisePropertyChanged("FUCodigoLocalidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FUCodigoLotacao {
            get {
                return this.FUCodigoLotacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.FUCodigoLotacaoField, value) != true)) {
                    this.FUCodigoLotacaoField = value;
                    this.RaisePropertyChanged("FUCodigoLotacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FUMATFUNC {
            get {
                return this.FUMATFUNCField;
            }
            set {
                if ((this.FUMATFUNCField.Equals(value) != true)) {
                    this.FUMATFUNCField = value;
                    this.RaisePropertyChanged("FUMATFUNC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FUNOMFUNC {
            get {
                return this.FUNOMFUNCField;
            }
            set {
                if ((object.ReferenceEquals(this.FUNOMFUNCField, value) != true)) {
                    this.FUNOMFUNCField = value;
                    this.RaisePropertyChanged("FUNOMFUNC");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ESTAGIARIO", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class ESTAGIARIO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ESCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ESCodigoLocalidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESCodigoLotacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESNomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ESCodigo {
            get {
                return this.ESCodigoField;
            }
            set {
                if ((this.ESCodigoField.Equals(value) != true)) {
                    this.ESCodigoField = value;
                    this.RaisePropertyChanged("ESCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ESCodigoLocalidade {
            get {
                return this.ESCodigoLocalidadeField;
            }
            set {
                if ((this.ESCodigoLocalidadeField.Equals(value) != true)) {
                    this.ESCodigoLocalidadeField = value;
                    this.RaisePropertyChanged("ESCodigoLocalidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ESCodigoLotacao {
            get {
                return this.ESCodigoLotacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.ESCodigoLotacaoField, value) != true)) {
                    this.ESCodigoLotacaoField = value;
                    this.RaisePropertyChanged("ESCodigoLotacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ESNome {
            get {
                return this.ESNomeField;
            }
            set {
                if ((object.ReferenceEquals(this.ESNomeField, value) != true)) {
                    this.ESNomeField = value;
                    this.RaisePropertyChanged("ESNome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TERCEIRO", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class TERCEIRO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TeCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeNomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeCodigo {
            get {
                return this.TeCodigoField;
            }
            set {
                if ((this.TeCodigoField.Equals(value) != true)) {
                    this.TeCodigoField = value;
                    this.RaisePropertyChanged("TeCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeNome {
            get {
                return this.TeNomeField;
            }
            set {
                if ((object.ReferenceEquals(this.TeNomeField, value) != true)) {
                    this.TeNomeField = value;
                    this.RaisePropertyChanged("TeNome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VISITANTE", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class VISITANTE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ViCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ViNomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ViCodigo {
            get {
                return this.ViCodigoField;
            }
            set {
                if ((this.ViCodigoField.Equals(value) != true)) {
                    this.ViCodigoField = value;
                    this.RaisePropertyChanged("ViCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ViNome {
            get {
                return this.ViNomeField;
            }
            set {
                if ((object.ReferenceEquals(this.ViNomeField, value) != true)) {
                    this.ViNomeField = value;
                    this.RaisePropertyChanged("ViNome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ROTAUSUARIO", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class ROTAUSUARIO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RUCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RUCodigoRotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RUCodigoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RUDataExpiracaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RUDataInicioPermissaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RUCodigo {
            get {
                return this.RUCodigoField;
            }
            set {
                if ((this.RUCodigoField.Equals(value) != true)) {
                    this.RUCodigoField = value;
                    this.RaisePropertyChanged("RUCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RUCodigoRota {
            get {
                return this.RUCodigoRotaField;
            }
            set {
                if ((this.RUCodigoRotaField.Equals(value) != true)) {
                    this.RUCodigoRotaField = value;
                    this.RaisePropertyChanged("RUCodigoRota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RUCodigoUsuario {
            get {
                return this.RUCodigoUsuarioField;
            }
            set {
                if ((this.RUCodigoUsuarioField.Equals(value) != true)) {
                    this.RUCodigoUsuarioField = value;
                    this.RaisePropertyChanged("RUCodigoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RUDataExpiracao {
            get {
                return this.RUDataExpiracaoField;
            }
            set {
                if ((this.RUDataExpiracaoField.Equals(value) != true)) {
                    this.RUDataExpiracaoField = value;
                    this.RaisePropertyChanged("RUDataExpiracao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RUDataInicioPermissao {
            get {
                return this.RUDataInicioPermissaoField;
            }
            set {
                if ((this.RUDataInicioPermissaoField.Equals(value) != true)) {
                    this.RUDataInicioPermissaoField = value;
                    this.RaisePropertyChanged("RUDataInicioPermissao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PONTOROTA", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class PONTOROTA : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PRCodigoPontoControleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PRCodigoRotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PROrdemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PRTempoMaxPermField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char PRTipoPontoControleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PRCodigoPontoControle {
            get {
                return this.PRCodigoPontoControleField;
            }
            set {
                if ((this.PRCodigoPontoControleField.Equals(value) != true)) {
                    this.PRCodigoPontoControleField = value;
                    this.RaisePropertyChanged("PRCodigoPontoControle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PRCodigoRota {
            get {
                return this.PRCodigoRotaField;
            }
            set {
                if ((this.PRCodigoRotaField.Equals(value) != true)) {
                    this.PRCodigoRotaField = value;
                    this.RaisePropertyChanged("PRCodigoRota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PROrdem {
            get {
                return this.PROrdemField;
            }
            set {
                if ((this.PROrdemField.Equals(value) != true)) {
                    this.PROrdemField = value;
                    this.RaisePropertyChanged("PROrdem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PRTempoMaxPerm {
            get {
                return this.PRTempoMaxPermField;
            }
            set {
                if ((this.PRTempoMaxPermField.Equals(value) != true)) {
                    this.PRTempoMaxPermField = value;
                    this.RaisePropertyChanged("PRTempoMaxPerm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char PRTipoPontoControle {
            get {
                return this.PRTipoPontoControleField;
            }
            set {
                if ((this.PRTipoPontoControleField.Equals(value) != true)) {
                    this.PRTipoPontoControleField = value;
                    this.RaisePropertyChanged("PRTipoPontoControle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ACESSOPONTOCONTROLE", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class ACESSOPONTOCONTROLE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> APAcessoForcadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int APCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> APCodigoCartaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int APCodigoPontoControleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> APCodigoUsuarioAcessoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> APCodigoUsuarioInterrompeAlarmeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> APCodigoUsuarioLiberaForcadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool APControlarSaidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime APDataAcessoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> APDataInterrupcaoAlarmeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> APDisparouAlarmeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APMotivoAcessoForcadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool APNegadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string APObservacaoInterrupcaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char APTipoPontoControleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> APAcessoForcado {
            get {
                return this.APAcessoForcadoField;
            }
            set {
                if ((this.APAcessoForcadoField.Equals(value) != true)) {
                    this.APAcessoForcadoField = value;
                    this.RaisePropertyChanged("APAcessoForcado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int APCodigo {
            get {
                return this.APCodigoField;
            }
            set {
                if ((this.APCodigoField.Equals(value) != true)) {
                    this.APCodigoField = value;
                    this.RaisePropertyChanged("APCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> APCodigoCartao {
            get {
                return this.APCodigoCartaoField;
            }
            set {
                if ((this.APCodigoCartaoField.Equals(value) != true)) {
                    this.APCodigoCartaoField = value;
                    this.RaisePropertyChanged("APCodigoCartao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int APCodigoPontoControle {
            get {
                return this.APCodigoPontoControleField;
            }
            set {
                if ((this.APCodigoPontoControleField.Equals(value) != true)) {
                    this.APCodigoPontoControleField = value;
                    this.RaisePropertyChanged("APCodigoPontoControle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> APCodigoUsuarioAcesso {
            get {
                return this.APCodigoUsuarioAcessoField;
            }
            set {
                if ((this.APCodigoUsuarioAcessoField.Equals(value) != true)) {
                    this.APCodigoUsuarioAcessoField = value;
                    this.RaisePropertyChanged("APCodigoUsuarioAcesso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> APCodigoUsuarioInterrompeAlarme {
            get {
                return this.APCodigoUsuarioInterrompeAlarmeField;
            }
            set {
                if ((this.APCodigoUsuarioInterrompeAlarmeField.Equals(value) != true)) {
                    this.APCodigoUsuarioInterrompeAlarmeField = value;
                    this.RaisePropertyChanged("APCodigoUsuarioInterrompeAlarme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> APCodigoUsuarioLiberaForcado {
            get {
                return this.APCodigoUsuarioLiberaForcadoField;
            }
            set {
                if ((this.APCodigoUsuarioLiberaForcadoField.Equals(value) != true)) {
                    this.APCodigoUsuarioLiberaForcadoField = value;
                    this.RaisePropertyChanged("APCodigoUsuarioLiberaForcado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool APControlarSaida {
            get {
                return this.APControlarSaidaField;
            }
            set {
                if ((this.APControlarSaidaField.Equals(value) != true)) {
                    this.APControlarSaidaField = value;
                    this.RaisePropertyChanged("APControlarSaida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime APDataAcesso {
            get {
                return this.APDataAcessoField;
            }
            set {
                if ((this.APDataAcessoField.Equals(value) != true)) {
                    this.APDataAcessoField = value;
                    this.RaisePropertyChanged("APDataAcesso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> APDataInterrupcaoAlarme {
            get {
                return this.APDataInterrupcaoAlarmeField;
            }
            set {
                if ((this.APDataInterrupcaoAlarmeField.Equals(value) != true)) {
                    this.APDataInterrupcaoAlarmeField = value;
                    this.RaisePropertyChanged("APDataInterrupcaoAlarme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> APDisparouAlarme {
            get {
                return this.APDisparouAlarmeField;
            }
            set {
                if ((this.APDisparouAlarmeField.Equals(value) != true)) {
                    this.APDisparouAlarmeField = value;
                    this.RaisePropertyChanged("APDisparouAlarme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APMotivoAcessoForcado {
            get {
                return this.APMotivoAcessoForcadoField;
            }
            set {
                if ((object.ReferenceEquals(this.APMotivoAcessoForcadoField, value) != true)) {
                    this.APMotivoAcessoForcadoField = value;
                    this.RaisePropertyChanged("APMotivoAcessoForcado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool APNegado {
            get {
                return this.APNegadoField;
            }
            set {
                if ((this.APNegadoField.Equals(value) != true)) {
                    this.APNegadoField = value;
                    this.RaisePropertyChanged("APNegado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string APObservacaoInterrupcao {
            get {
                return this.APObservacaoInterrupcaoField;
            }
            set {
                if ((object.ReferenceEquals(this.APObservacaoInterrupcaoField, value) != true)) {
                    this.APObservacaoInterrupcaoField = value;
                    this.RaisePropertyChanged("APObservacaoInterrupcao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char APTipoPontoControle {
            get {
                return this.APTipoPontoControleField;
            }
            set {
                if ((this.APTipoPontoControleField.Equals(value) != true)) {
                    this.APTipoPontoControleField = value;
                    this.RaisePropertyChanged("APTipoPontoControle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HASHDIGITAL", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class HASHDIGITAL : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HaCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HaCodigoDigitalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HaCodigoEquipamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HaCodigoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HaCredencialBiometricaTextualField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HaCodigo {
            get {
                return this.HaCodigoField;
            }
            set {
                if ((this.HaCodigoField.Equals(value) != true)) {
                    this.HaCodigoField = value;
                    this.RaisePropertyChanged("HaCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HaCodigoDigital {
            get {
                return this.HaCodigoDigitalField;
            }
            set {
                if ((this.HaCodigoDigitalField.Equals(value) != true)) {
                    this.HaCodigoDigitalField = value;
                    this.RaisePropertyChanged("HaCodigoDigital");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HaCodigoEquipamento {
            get {
                return this.HaCodigoEquipamentoField;
            }
            set {
                if ((this.HaCodigoEquipamentoField.Equals(value) != true)) {
                    this.HaCodigoEquipamentoField = value;
                    this.RaisePropertyChanged("HaCodigoEquipamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HaCodigoUsuario {
            get {
                return this.HaCodigoUsuarioField;
            }
            set {
                if ((this.HaCodigoUsuarioField.Equals(value) != true)) {
                    this.HaCodigoUsuarioField = value;
                    this.RaisePropertyChanged("HaCodigoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HaCredencialBiometricaTextual {
            get {
                return this.HaCredencialBiometricaTextualField;
            }
            set {
                if ((object.ReferenceEquals(this.HaCredencialBiometricaTextualField, value) != true)) {
                    this.HaCredencialBiometricaTextualField = value;
                    this.RaisePropertyChanged("HaCredencialBiometricaTextual");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DIGITAL", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class DIGITAL : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DiCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DiDataVencimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char DiDedoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char DiMaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DiCodigo {
            get {
                return this.DiCodigoField;
            }
            set {
                if ((this.DiCodigoField.Equals(value) != true)) {
                    this.DiCodigoField = value;
                    this.RaisePropertyChanged("DiCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DiDataVencimento {
            get {
                return this.DiDataVencimentoField;
            }
            set {
                if ((this.DiDataVencimentoField.Equals(value) != true)) {
                    this.DiDataVencimentoField = value;
                    this.RaisePropertyChanged("DiDataVencimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char DiDedo {
            get {
                return this.DiDedoField;
            }
            set {
                if ((this.DiDedoField.Equals(value) != true)) {
                    this.DiDedoField = value;
                    this.RaisePropertyChanged("DiDedo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char DiMao {
            get {
                return this.DiMaoField;
            }
            set {
                if ((this.DiMaoField.Equals(value) != true)) {
                    this.DiMaoField = value;
                    this.RaisePropertyChanged("DiMao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CARTAO", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class CARTAO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> CrBloqueadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CrCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CrCodigoFabricanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CrDataBloqueioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CrMotivoBloqueioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CrNumeroCartaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char CrTipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> CrBloqueado {
            get {
                return this.CrBloqueadoField;
            }
            set {
                if ((this.CrBloqueadoField.Equals(value) != true)) {
                    this.CrBloqueadoField = value;
                    this.RaisePropertyChanged("CrBloqueado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CrCodigo {
            get {
                return this.CrCodigoField;
            }
            set {
                if ((this.CrCodigoField.Equals(value) != true)) {
                    this.CrCodigoField = value;
                    this.RaisePropertyChanged("CrCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CrCodigoFabricante {
            get {
                return this.CrCodigoFabricanteField;
            }
            set {
                if ((this.CrCodigoFabricanteField.Equals(value) != true)) {
                    this.CrCodigoFabricanteField = value;
                    this.RaisePropertyChanged("CrCodigoFabricante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CrDataBloqueio {
            get {
                return this.CrDataBloqueioField;
            }
            set {
                if ((this.CrDataBloqueioField.Equals(value) != true)) {
                    this.CrDataBloqueioField = value;
                    this.RaisePropertyChanged("CrDataBloqueio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CrMotivoBloqueio {
            get {
                return this.CrMotivoBloqueioField;
            }
            set {
                if ((object.ReferenceEquals(this.CrMotivoBloqueioField, value) != true)) {
                    this.CrMotivoBloqueioField = value;
                    this.RaisePropertyChanged("CrMotivoBloqueio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CrNumeroCartao {
            get {
                return this.CrNumeroCartaoField;
            }
            set {
                if ((object.ReferenceEquals(this.CrNumeroCartaoField, value) != true)) {
                    this.CrNumeroCartaoField = value;
                    this.RaisePropertyChanged("CrNumeroCartao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char CrTipo {
            get {
                return this.CrTipoField;
            }
            set {
                if ((this.CrTipoField.Equals(value) != true)) {
                    this.CrTipoField = value;
                    this.RaisePropertyChanged("CrTipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CARTAOUSUARIO", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class CARTAOUSUARIO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CSCODIGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CSCodigoCartaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CSCodigoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CSDataDevolucaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CSDataEntregaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CSDataExpiracaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> CSDevolvidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CSObservacaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CSCODIGO {
            get {
                return this.CSCODIGOField;
            }
            set {
                if ((this.CSCODIGOField.Equals(value) != true)) {
                    this.CSCODIGOField = value;
                    this.RaisePropertyChanged("CSCODIGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CSCodigoCartao {
            get {
                return this.CSCodigoCartaoField;
            }
            set {
                if ((this.CSCodigoCartaoField.Equals(value) != true)) {
                    this.CSCodigoCartaoField = value;
                    this.RaisePropertyChanged("CSCodigoCartao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CSCodigoUsuario {
            get {
                return this.CSCodigoUsuarioField;
            }
            set {
                if ((this.CSCodigoUsuarioField.Equals(value) != true)) {
                    this.CSCodigoUsuarioField = value;
                    this.RaisePropertyChanged("CSCodigoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CSDataDevolucao {
            get {
                return this.CSDataDevolucaoField;
            }
            set {
                if ((this.CSDataDevolucaoField.Equals(value) != true)) {
                    this.CSDataDevolucaoField = value;
                    this.RaisePropertyChanged("CSDataDevolucao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CSDataEntrega {
            get {
                return this.CSDataEntregaField;
            }
            set {
                if ((this.CSDataEntregaField.Equals(value) != true)) {
                    this.CSDataEntregaField = value;
                    this.RaisePropertyChanged("CSDataEntrega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CSDataExpiracao {
            get {
                return this.CSDataExpiracaoField;
            }
            set {
                if ((this.CSDataExpiracaoField.Equals(value) != true)) {
                    this.CSDataExpiracaoField = value;
                    this.RaisePropertyChanged("CSDataExpiracao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> CSDevolvido {
            get {
                return this.CSDevolvidoField;
            }
            set {
                if ((this.CSDevolvidoField.Equals(value) != true)) {
                    this.CSDevolvidoField = value;
                    this.RaisePropertyChanged("CSDevolvido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CSObservacao {
            get {
                return this.CSObservacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.CSObservacaoField, value) != true)) {
                    this.CSObservacaoField = value;
                    this.RaisePropertyChanged("CSObservacao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CONTRATOTERCEIRO", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class CONTRATOTERCEIRO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CTCNPJFornecedorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CTCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CTCodigoLocalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CTCodigoLotacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CTCodigoTerceiroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CTDataExpiracaoContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CTDataInicioContratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CTObservacaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CTCNPJFornecedor {
            get {
                return this.CTCNPJFornecedorField;
            }
            set {
                if ((object.ReferenceEquals(this.CTCNPJFornecedorField, value) != true)) {
                    this.CTCNPJFornecedorField = value;
                    this.RaisePropertyChanged("CTCNPJFornecedor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CTCodigo {
            get {
                return this.CTCodigoField;
            }
            set {
                if ((this.CTCodigoField.Equals(value) != true)) {
                    this.CTCodigoField = value;
                    this.RaisePropertyChanged("CTCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CTCodigoLocal {
            get {
                return this.CTCodigoLocalField;
            }
            set {
                if ((this.CTCodigoLocalField.Equals(value) != true)) {
                    this.CTCodigoLocalField = value;
                    this.RaisePropertyChanged("CTCodigoLocal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CTCodigoLotacao {
            get {
                return this.CTCodigoLotacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.CTCodigoLotacaoField, value) != true)) {
                    this.CTCodigoLotacaoField = value;
                    this.RaisePropertyChanged("CTCodigoLotacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CTCodigoTerceiro {
            get {
                return this.CTCodigoTerceiroField;
            }
            set {
                if ((this.CTCodigoTerceiroField.Equals(value) != true)) {
                    this.CTCodigoTerceiroField = value;
                    this.RaisePropertyChanged("CTCodigoTerceiro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CTDataExpiracaoContrato {
            get {
                return this.CTDataExpiracaoContratoField;
            }
            set {
                if ((this.CTDataExpiracaoContratoField.Equals(value) != true)) {
                    this.CTDataExpiracaoContratoField = value;
                    this.RaisePropertyChanged("CTDataExpiracaoContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CTDataInicioContrato {
            get {
                return this.CTDataInicioContratoField;
            }
            set {
                if ((this.CTDataInicioContratoField.Equals(value) != true)) {
                    this.CTDataInicioContratoField = value;
                    this.RaisePropertyChanged("CTDataInicioContrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CTObservacao {
            get {
                return this.CTObservacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.CTObservacaoField, value) != true)) {
                    this.CTObservacaoField = value;
                    this.RaisePropertyChanged("CTObservacao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vw_EquipamentoPonto", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class vw_EquipamentoPonto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EPCodigoPontoControleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EPCodigoTipoEquipamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char EPCodigoTipoPontoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EPNumeroPortaReleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> EPObrigatorioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PoNomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TEDescricaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EPCodigoPontoControle {
            get {
                return this.EPCodigoPontoControleField;
            }
            set {
                if ((this.EPCodigoPontoControleField.Equals(value) != true)) {
                    this.EPCodigoPontoControleField = value;
                    this.RaisePropertyChanged("EPCodigoPontoControle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EPCodigoTipoEquipamento {
            get {
                return this.EPCodigoTipoEquipamentoField;
            }
            set {
                if ((this.EPCodigoTipoEquipamentoField.Equals(value) != true)) {
                    this.EPCodigoTipoEquipamentoField = value;
                    this.RaisePropertyChanged("EPCodigoTipoEquipamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char EPCodigoTipoPonto {
            get {
                return this.EPCodigoTipoPontoField;
            }
            set {
                if ((this.EPCodigoTipoPontoField.Equals(value) != true)) {
                    this.EPCodigoTipoPontoField = value;
                    this.RaisePropertyChanged("EPCodigoTipoPonto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EPNumeroPortaRele {
            get {
                return this.EPNumeroPortaReleField;
            }
            set {
                if ((this.EPNumeroPortaReleField.Equals(value) != true)) {
                    this.EPNumeroPortaReleField = value;
                    this.RaisePropertyChanged("EPNumeroPortaRele");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> EPObrigatorio {
            get {
                return this.EPObrigatorioField;
            }
            set {
                if ((this.EPObrigatorioField.Equals(value) != true)) {
                    this.EPObrigatorioField = value;
                    this.RaisePropertyChanged("EPObrigatorio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PoNome {
            get {
                return this.PoNomeField;
            }
            set {
                if ((object.ReferenceEquals(this.PoNomeField, value) != true)) {
                    this.PoNomeField = value;
                    this.RaisePropertyChanged("PoNome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TEDescricao {
            get {
                return this.TEDescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.TEDescricaoField, value) != true)) {
                    this.TEDescricaoField = value;
                    this.RaisePropertyChanged("TEDescricao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vw_EquipamentoUsuario", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class vw_EquipamentoUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EUSCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EUSCodigoEquipamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EUSCodigoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EUSDataFimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EUSDataInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EqNomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EqTAGRFIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EUSCodigo {
            get {
                return this.EUSCodigoField;
            }
            set {
                if ((this.EUSCodigoField.Equals(value) != true)) {
                    this.EUSCodigoField = value;
                    this.RaisePropertyChanged("EUSCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EUSCodigoEquipamento {
            get {
                return this.EUSCodigoEquipamentoField;
            }
            set {
                if ((this.EUSCodigoEquipamentoField.Equals(value) != true)) {
                    this.EUSCodigoEquipamentoField = value;
                    this.RaisePropertyChanged("EUSCodigoEquipamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EUSCodigoUsuario {
            get {
                return this.EUSCodigoUsuarioField;
            }
            set {
                if ((this.EUSCodigoUsuarioField.Equals(value) != true)) {
                    this.EUSCodigoUsuarioField = value;
                    this.RaisePropertyChanged("EUSCodigoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EUSDataFim {
            get {
                return this.EUSDataFimField;
            }
            set {
                if ((this.EUSDataFimField.Equals(value) != true)) {
                    this.EUSDataFimField = value;
                    this.RaisePropertyChanged("EUSDataFim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EUSDataInicio {
            get {
                return this.EUSDataInicioField;
            }
            set {
                if ((this.EUSDataInicioField.Equals(value) != true)) {
                    this.EUSDataInicioField = value;
                    this.RaisePropertyChanged("EUSDataInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EqNome {
            get {
                return this.EqNomeField;
            }
            set {
                if ((object.ReferenceEquals(this.EqNomeField, value) != true)) {
                    this.EqNomeField = value;
                    this.RaisePropertyChanged("EqNome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EqTAGRFID {
            get {
                return this.EqTAGRFIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EqTAGRFIDField, value) != true)) {
                    this.EqTAGRFIDField = value;
                    this.RaisePropertyChanged("EqTAGRFID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CPonto.ICPonto")]
    public interface ICPonto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICPonto/SelecionaPKPontoControle", ReplyAction="http://tempuri.org/ICPonto/SelecionaPKPontoControleResponse")]
        ACESSO.PONTOCONTROLE.CPonto.PONTOCONTROLE SelecionaPKPontoControle(int Codigo, string Tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICPonto/SelecionaUsuario", ReplyAction="http://tempuri.org/ICPonto/SelecionaUsuarioResponse")]
        ACESSO.PONTOCONTROLE.CPonto.USUARIO SelecionaUsuario(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICPonto/SelecionaFuncionario", ReplyAction="http://tempuri.org/ICPonto/SelecionaFuncionarioResponse")]
        ACESSO.PONTOCONTROLE.CPonto.FUNCIONARIO SelecionaFuncionario(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICPonto/SelecionaEstagiario", ReplyAction="http://tempuri.org/ICPonto/SelecionaEstagiarioResponse")]
        ACESSO.PONTOCONTROLE.CPonto.ESTAGIARIO SelecionaEstagiario(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICPonto/SelecionaTerceiro", ReplyAction="http://tempuri.org/ICPonto/SelecionaTerceiroResponse")]
        ACESSO.PONTOCONTROLE.CPonto.TERCEIRO SelecionaTerceiro(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICPonto/SelecionaVisitante", ReplyAction="http://tempuri.org/ICPonto/SelecionaVisitanteResponse")]
        ACESSO.PONTOCONTROLE.CPonto.VISITANTE SelecionaVisitante(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICPonto/RotasUsuario", ReplyAction="http://tempuri.org/ICPonto/RotasUsuarioResponse")]
        ACESSO.PONTOCONTROLE.CPonto.ROTAUSUARIO[] RotasUsuario(int CodigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICPonto/PontosRota", ReplyAction="http://tempuri.org/ICPonto/PontosRotaResponse")]
        ACESSO.PONTOCONTROLE.CPonto.PONTOROTA[] PontosRota(int CodigoRota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICPonto/PossuiPermissaoPonto", ReplyAction="http://tempuri.org/ICPonto/PossuiPermissaoPontoResponse")]
        bool PossuiPermissaoPonto(int CodigoUsuario, int CodigoPonto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICPonto/IncluirAcesso", ReplyAction="http://tempuri.org/ICPonto/IncluirAcessoResponse")]
        void IncluirAcesso(ACESSO.PONTOCONTROLE.CPonto.ACESSOPONTOCONTROLE oAcessoPontoControle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICPonto/ListaHash", ReplyAction="http://tempuri.org/ICPonto/ListaHashResponse")]
        ACESSO.PONTOCONTROLE.CPonto.HASHDIGITAL[] ListaHash();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICPonto/SelecionaHash", ReplyAction="http://tempuri.org/ICPonto/SelecionaHashResponse")]
        ACESSO.PONTOCONTROLE.CPonto.HASHDIGITAL SelecionaHash(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICPonto/SelecionaHashUsuario", ReplyAction="http://tempuri.org/ICPonto/SelecionaHashUsuarioResponse")]
        ACESSO.PONTOCONTROLE.CPonto.HASHDIGITAL[] SelecionaHashUsuario(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICPonto/SelecionaDigital", ReplyAction="http://tempuri.org/ICPonto/SelecionaDigitalResponse")]
        ACESSO.PONTOCONTROLE.CPonto.DIGITAL SelecionaDigital(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICPonto/SelecionaUsuarioRede", ReplyAction="http://tempuri.org/ICPonto/SelecionaUsuarioRedeResponse")]
        ACESSO.PONTOCONTROLE.CPonto.USUARIO SelecionaUsuarioRede(string Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICPonto/SelecionaCartao", ReplyAction="http://tempuri.org/ICPonto/SelecionaCartaoResponse")]
        ACESSO.PONTOCONTROLE.CPonto.CARTAO SelecionaCartao(out ACESSO.PONTOCONTROLE.CPonto.CARTAOUSUARIO oCartaoUsuario, string NumeroCartao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICPonto/ContratoValidoTerceiro", ReplyAction="http://tempuri.org/ICPonto/ContratoValidoTerceiroResponse")]
        ACESSO.PONTOCONTROLE.CPonto.CONTRATOTERCEIRO ContratoValidoTerceiro(int CodigoTerceiro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICPonto/ListaEquipamentoPonto", ReplyAction="http://tempuri.org/ICPonto/ListaEquipamentoPontoResponse")]
        ACESSO.PONTOCONTROLE.CPonto.vw_EquipamentoPonto[] ListaEquipamentoPonto(int CodigoPonto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICPonto/ListaEquipamentoUsuarioTAG", ReplyAction="http://tempuri.org/ICPonto/ListaEquipamentoUsuarioTAGResponse")]
        ACESSO.PONTOCONTROLE.CPonto.vw_EquipamentoUsuario ListaEquipamentoUsuarioTAG(int CodigoUsuario, string TAG);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICPontoChannel : ACESSO.PONTOCONTROLE.CPonto.ICPonto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CPontoClient : System.ServiceModel.ClientBase<ACESSO.PONTOCONTROLE.CPonto.ICPonto>, ACESSO.PONTOCONTROLE.CPonto.ICPonto {
        
        public CPontoClient() {
        }
        
        public CPontoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CPontoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CPontoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CPontoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ACESSO.PONTOCONTROLE.CPonto.PONTOCONTROLE SelecionaPKPontoControle(int Codigo, string Tipo) {
            return base.Channel.SelecionaPKPontoControle(Codigo, Tipo);
        }
        
        public ACESSO.PONTOCONTROLE.CPonto.USUARIO SelecionaUsuario(int Codigo) {
            return base.Channel.SelecionaUsuario(Codigo);
        }
        
        public ACESSO.PONTOCONTROLE.CPonto.FUNCIONARIO SelecionaFuncionario(int Codigo) {
            return base.Channel.SelecionaFuncionario(Codigo);
        }
        
        public ACESSO.PONTOCONTROLE.CPonto.ESTAGIARIO SelecionaEstagiario(int Codigo) {
            return base.Channel.SelecionaEstagiario(Codigo);
        }
        
        public ACESSO.PONTOCONTROLE.CPonto.TERCEIRO SelecionaTerceiro(int Codigo) {
            return base.Channel.SelecionaTerceiro(Codigo);
        }
        
        public ACESSO.PONTOCONTROLE.CPonto.VISITANTE SelecionaVisitante(int Codigo) {
            return base.Channel.SelecionaVisitante(Codigo);
        }
        
        public ACESSO.PONTOCONTROLE.CPonto.ROTAUSUARIO[] RotasUsuario(int CodigoUsuario) {
            return base.Channel.RotasUsuario(CodigoUsuario);
        }
        
        public ACESSO.PONTOCONTROLE.CPonto.PONTOROTA[] PontosRota(int CodigoRota) {
            return base.Channel.PontosRota(CodigoRota);
        }
        
        public bool PossuiPermissaoPonto(int CodigoUsuario, int CodigoPonto) {
            return base.Channel.PossuiPermissaoPonto(CodigoUsuario, CodigoPonto);
        }
        
        public void IncluirAcesso(ACESSO.PONTOCONTROLE.CPonto.ACESSOPONTOCONTROLE oAcessoPontoControle) {
            base.Channel.IncluirAcesso(oAcessoPontoControle);
        }
        
        public ACESSO.PONTOCONTROLE.CPonto.HASHDIGITAL[] ListaHash() {
            return base.Channel.ListaHash();
        }
        
        public ACESSO.PONTOCONTROLE.CPonto.HASHDIGITAL SelecionaHash(int Codigo) {
            return base.Channel.SelecionaHash(Codigo);
        }
        
        public ACESSO.PONTOCONTROLE.CPonto.HASHDIGITAL[] SelecionaHashUsuario(int Codigo) {
            return base.Channel.SelecionaHashUsuario(Codigo);
        }
        
        public ACESSO.PONTOCONTROLE.CPonto.DIGITAL SelecionaDigital(int Codigo) {
            return base.Channel.SelecionaDigital(Codigo);
        }
        
        public ACESSO.PONTOCONTROLE.CPonto.USUARIO SelecionaUsuarioRede(string Codigo) {
            return base.Channel.SelecionaUsuarioRede(Codigo);
        }
        
        public ACESSO.PONTOCONTROLE.CPonto.CARTAO SelecionaCartao(out ACESSO.PONTOCONTROLE.CPonto.CARTAOUSUARIO oCartaoUsuario, string NumeroCartao) {
            return base.Channel.SelecionaCartao(out oCartaoUsuario, NumeroCartao);
        }
        
        public ACESSO.PONTOCONTROLE.CPonto.CONTRATOTERCEIRO ContratoValidoTerceiro(int CodigoTerceiro) {
            return base.Channel.ContratoValidoTerceiro(CodigoTerceiro);
        }
        
        public ACESSO.PONTOCONTROLE.CPonto.vw_EquipamentoPonto[] ListaEquipamentoPonto(int CodigoPonto) {
            return base.Channel.ListaEquipamentoPonto(CodigoPonto);
        }
        
        public ACESSO.PONTOCONTROLE.CPonto.vw_EquipamentoUsuario ListaEquipamentoUsuarioTAG(int CodigoUsuario, string TAG) {
            return base.Channel.ListaEquipamentoUsuarioTAG(CodigoUsuario, TAG);
        }
    }
}
