//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACESSO.ADMINISTRATIVO.CTipoEquipamento {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TIPOEQUIPAMENTO", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class TIPOEQUIPAMENTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TECodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TEDescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> TEEPIField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TECodigo {
            get {
                return this.TECodigoField;
            }
            set {
                if ((this.TECodigoField.Equals(value) != true)) {
                    this.TECodigoField = value;
                    this.RaisePropertyChanged("TECodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TEDescricao {
            get {
                return this.TEDescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.TEDescricaoField, value) != true)) {
                    this.TEDescricaoField = value;
                    this.RaisePropertyChanged("TEDescricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> TEEPI {
            get {
                return this.TEEPIField;
            }
            set {
                if ((this.TEEPIField.Equals(value) != true)) {
                    this.TEEPIField = value;
                    this.RaisePropertyChanged("TEEPI");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CTipoEquipamento.ICTipoEquipamento")]
    public interface ICTipoEquipamento {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICTipoEquipamento/ListarTodosTiposEquipamento", ReplyAction="http://tempuri.org/ICTipoEquipamento/ListarTodosTiposEquipamentoResponse")]
        ACESSO.ADMINISTRATIVO.CTipoEquipamento.TIPOEQUIPAMENTO[] ListarTodosTiposEquipamento();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICTipoEquipamento/SelecionaPKTipoEquipamento", ReplyAction="http://tempuri.org/ICTipoEquipamento/SelecionaPKTipoEquipamentoResponse")]
        ACESSO.ADMINISTRATIVO.CTipoEquipamento.TIPOEQUIPAMENTO SelecionaPKTipoEquipamento(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICTipoEquipamento/Incluir", ReplyAction="http://tempuri.org/ICTipoEquipamento/IncluirResponse")]
        void Incluir(ACESSO.ADMINISTRATIVO.CTipoEquipamento.TIPOEQUIPAMENTO oTIPOEQUIPAMENTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICTipoEquipamento/Alterar", ReplyAction="http://tempuri.org/ICTipoEquipamento/AlterarResponse")]
        void Alterar(ACESSO.ADMINISTRATIVO.CTipoEquipamento.TIPOEQUIPAMENTO oTIPOEQUIPAMENTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICTipoEquipamento/Excluir", ReplyAction="http://tempuri.org/ICTipoEquipamento/ExcluirResponse")]
        void Excluir(ACESSO.ADMINISTRATIVO.CTipoEquipamento.TIPOEQUIPAMENTO oTIPOEQUIPAMENTO);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICTipoEquipamentoChannel : ACESSO.ADMINISTRATIVO.CTipoEquipamento.ICTipoEquipamento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CTipoEquipamentoClient : System.ServiceModel.ClientBase<ACESSO.ADMINISTRATIVO.CTipoEquipamento.ICTipoEquipamento>, ACESSO.ADMINISTRATIVO.CTipoEquipamento.ICTipoEquipamento {
        
        public CTipoEquipamentoClient() {
        }
        
        public CTipoEquipamentoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CTipoEquipamentoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CTipoEquipamentoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CTipoEquipamentoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ACESSO.ADMINISTRATIVO.CTipoEquipamento.TIPOEQUIPAMENTO[] ListarTodosTiposEquipamento() {
            return base.Channel.ListarTodosTiposEquipamento();
        }
        
        public ACESSO.ADMINISTRATIVO.CTipoEquipamento.TIPOEQUIPAMENTO SelecionaPKTipoEquipamento(int Codigo) {
            return base.Channel.SelecionaPKTipoEquipamento(Codigo);
        }
        
        public void Incluir(ACESSO.ADMINISTRATIVO.CTipoEquipamento.TIPOEQUIPAMENTO oTIPOEQUIPAMENTO) {
            base.Channel.Incluir(oTIPOEQUIPAMENTO);
        }
        
        public void Alterar(ACESSO.ADMINISTRATIVO.CTipoEquipamento.TIPOEQUIPAMENTO oTIPOEQUIPAMENTO) {
            base.Channel.Alterar(oTIPOEQUIPAMENTO);
        }
        
        public void Excluir(ACESSO.ADMINISTRATIVO.CTipoEquipamento.TIPOEQUIPAMENTO oTIPOEQUIPAMENTO) {
            base.Channel.Excluir(oTIPOEQUIPAMENTO);
        }
    }
}
