//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACESSO.ADMINISTRATIVO.CRota {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ROTA", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class ROTA : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ROBloqueadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ROCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RODescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ROMotivoBloqueioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RONomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> ROBloqueada {
            get {
                return this.ROBloqueadaField;
            }
            set {
                if ((this.ROBloqueadaField.Equals(value) != true)) {
                    this.ROBloqueadaField = value;
                    this.RaisePropertyChanged("ROBloqueada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ROCodigo {
            get {
                return this.ROCodigoField;
            }
            set {
                if ((this.ROCodigoField.Equals(value) != true)) {
                    this.ROCodigoField = value;
                    this.RaisePropertyChanged("ROCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RODescricao {
            get {
                return this.RODescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.RODescricaoField, value) != true)) {
                    this.RODescricaoField = value;
                    this.RaisePropertyChanged("RODescricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ROMotivoBloqueio {
            get {
                return this.ROMotivoBloqueioField;
            }
            set {
                if ((object.ReferenceEquals(this.ROMotivoBloqueioField, value) != true)) {
                    this.ROMotivoBloqueioField = value;
                    this.RaisePropertyChanged("ROMotivoBloqueio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RONome {
            get {
                return this.RONomeField;
            }
            set {
                if ((object.ReferenceEquals(this.RONomeField, value) != true)) {
                    this.RONomeField = value;
                    this.RaisePropertyChanged("RONome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PONTOCONTROLE", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class PONTOCONTROLE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PoBiometriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PoCartaoRFIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PoCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PoControlaSaidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PoDescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PoDisparaAlarmeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PoNomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PoObservacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PoPermiteLiberacaoForcadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PoQtdMediaPessoasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PoQtdVerificaEquipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PoSenhaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PoSmartCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> PoTentativaIndevidaDisparaAlarmeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char PoTipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PoBiometria {
            get {
                return this.PoBiometriaField;
            }
            set {
                if ((this.PoBiometriaField.Equals(value) != true)) {
                    this.PoBiometriaField = value;
                    this.RaisePropertyChanged("PoBiometria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PoCartaoRFID {
            get {
                return this.PoCartaoRFIDField;
            }
            set {
                if ((this.PoCartaoRFIDField.Equals(value) != true)) {
                    this.PoCartaoRFIDField = value;
                    this.RaisePropertyChanged("PoCartaoRFID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PoCodigo {
            get {
                return this.PoCodigoField;
            }
            set {
                if ((this.PoCodigoField.Equals(value) != true)) {
                    this.PoCodigoField = value;
                    this.RaisePropertyChanged("PoCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PoControlaSaida {
            get {
                return this.PoControlaSaidaField;
            }
            set {
                if ((this.PoControlaSaidaField.Equals(value) != true)) {
                    this.PoControlaSaidaField = value;
                    this.RaisePropertyChanged("PoControlaSaida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PoDescricao {
            get {
                return this.PoDescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.PoDescricaoField, value) != true)) {
                    this.PoDescricaoField = value;
                    this.RaisePropertyChanged("PoDescricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PoDisparaAlarme {
            get {
                return this.PoDisparaAlarmeField;
            }
            set {
                if ((this.PoDisparaAlarmeField.Equals(value) != true)) {
                    this.PoDisparaAlarmeField = value;
                    this.RaisePropertyChanged("PoDisparaAlarme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PoNome {
            get {
                return this.PoNomeField;
            }
            set {
                if ((object.ReferenceEquals(this.PoNomeField, value) != true)) {
                    this.PoNomeField = value;
                    this.RaisePropertyChanged("PoNome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PoObservacao {
            get {
                return this.PoObservacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.PoObservacaoField, value) != true)) {
                    this.PoObservacaoField = value;
                    this.RaisePropertyChanged("PoObservacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PoPermiteLiberacaoForcada {
            get {
                return this.PoPermiteLiberacaoForcadaField;
            }
            set {
                if ((this.PoPermiteLiberacaoForcadaField.Equals(value) != true)) {
                    this.PoPermiteLiberacaoForcadaField = value;
                    this.RaisePropertyChanged("PoPermiteLiberacaoForcada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PoQtdMediaPessoas {
            get {
                return this.PoQtdMediaPessoasField;
            }
            set {
                if ((this.PoQtdMediaPessoasField.Equals(value) != true)) {
                    this.PoQtdMediaPessoasField = value;
                    this.RaisePropertyChanged("PoQtdMediaPessoas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PoQtdVerificaEquip {
            get {
                return this.PoQtdVerificaEquipField;
            }
            set {
                if ((this.PoQtdVerificaEquipField.Equals(value) != true)) {
                    this.PoQtdVerificaEquipField = value;
                    this.RaisePropertyChanged("PoQtdVerificaEquip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PoSenha {
            get {
                return this.PoSenhaField;
            }
            set {
                if ((this.PoSenhaField.Equals(value) != true)) {
                    this.PoSenhaField = value;
                    this.RaisePropertyChanged("PoSenha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PoSmartCard {
            get {
                return this.PoSmartCardField;
            }
            set {
                if ((this.PoSmartCardField.Equals(value) != true)) {
                    this.PoSmartCardField = value;
                    this.RaisePropertyChanged("PoSmartCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> PoTentativaIndevidaDisparaAlarme {
            get {
                return this.PoTentativaIndevidaDisparaAlarmeField;
            }
            set {
                if ((this.PoTentativaIndevidaDisparaAlarmeField.Equals(value) != true)) {
                    this.PoTentativaIndevidaDisparaAlarmeField = value;
                    this.RaisePropertyChanged("PoTentativaIndevidaDisparaAlarme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char PoTipo {
            get {
                return this.PoTipoField;
            }
            set {
                if ((this.PoTipoField.Equals(value) != true)) {
                    this.PoTipoField = value;
                    this.RaisePropertyChanged("PoTipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PONTOROTA", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class PONTOROTA : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PRCodigoPontoControleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PRCodigoRotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PROrdemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PRTempoMaxPermField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char PRTipoPontoControleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PRCodigoPontoControle {
            get {
                return this.PRCodigoPontoControleField;
            }
            set {
                if ((this.PRCodigoPontoControleField.Equals(value) != true)) {
                    this.PRCodigoPontoControleField = value;
                    this.RaisePropertyChanged("PRCodigoPontoControle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PRCodigoRota {
            get {
                return this.PRCodigoRotaField;
            }
            set {
                if ((this.PRCodigoRotaField.Equals(value) != true)) {
                    this.PRCodigoRotaField = value;
                    this.RaisePropertyChanged("PRCodigoRota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PROrdem {
            get {
                return this.PROrdemField;
            }
            set {
                if ((this.PROrdemField.Equals(value) != true)) {
                    this.PROrdemField = value;
                    this.RaisePropertyChanged("PROrdem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PRTempoMaxPerm {
            get {
                return this.PRTempoMaxPermField;
            }
            set {
                if ((this.PRTempoMaxPermField.Equals(value) != true)) {
                    this.PRTempoMaxPermField = value;
                    this.RaisePropertyChanged("PRTempoMaxPerm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char PRTipoPontoControle {
            get {
                return this.PRTipoPontoControleField;
            }
            set {
                if ((this.PRTipoPontoControleField.Equals(value) != true)) {
                    this.PRTipoPontoControleField = value;
                    this.RaisePropertyChanged("PRTipoPontoControle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vw_PontoRota", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class vw_PontoRota : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PRCodigoPontoControleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PRCodigoRotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PROrdemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PRTempoMaxPermField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char PRTipoPontoControleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PoNomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PRCodigoPontoControle {
            get {
                return this.PRCodigoPontoControleField;
            }
            set {
                if ((this.PRCodigoPontoControleField.Equals(value) != true)) {
                    this.PRCodigoPontoControleField = value;
                    this.RaisePropertyChanged("PRCodigoPontoControle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PRCodigoRota {
            get {
                return this.PRCodigoRotaField;
            }
            set {
                if ((this.PRCodigoRotaField.Equals(value) != true)) {
                    this.PRCodigoRotaField = value;
                    this.RaisePropertyChanged("PRCodigoRota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PROrdem {
            get {
                return this.PROrdemField;
            }
            set {
                if ((this.PROrdemField.Equals(value) != true)) {
                    this.PROrdemField = value;
                    this.RaisePropertyChanged("PROrdem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PRTempoMaxPerm {
            get {
                return this.PRTempoMaxPermField;
            }
            set {
                if ((this.PRTempoMaxPermField.Equals(value) != true)) {
                    this.PRTempoMaxPermField = value;
                    this.RaisePropertyChanged("PRTempoMaxPerm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char PRTipoPontoControle {
            get {
                return this.PRTipoPontoControleField;
            }
            set {
                if ((this.PRTipoPontoControleField.Equals(value) != true)) {
                    this.PRTipoPontoControleField = value;
                    this.RaisePropertyChanged("PRTipoPontoControle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PoNome {
            get {
                return this.PoNomeField;
            }
            set {
                if ((object.ReferenceEquals(this.PoNomeField, value) != true)) {
                    this.PoNomeField = value;
                    this.RaisePropertyChanged("PoNome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CRota.ICRota")]
    public interface ICRota {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRota/ListarTodasRotas", ReplyAction="http://tempuri.org/ICRota/ListarTodasRotasResponse")]
        ACESSO.ADMINISTRATIVO.CRota.ROTA[] ListarTodasRotas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRota/ListarPontosControleTipo", ReplyAction="http://tempuri.org/ICRota/ListarPontosControleTipoResponse")]
        ACESSO.ADMINISTRATIVO.CRota.PONTOCONTROLE[] ListarPontosControleTipo(char TipoPonto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRota/SelecionaPKROTA", ReplyAction="http://tempuri.org/ICRota/SelecionaPKROTAResponse")]
        ACESSO.ADMINISTRATIVO.CRota.ROTA SelecionaPKROTA(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRota/Incluir", ReplyAction="http://tempuri.org/ICRota/IncluirResponse")]
        int Incluir(ACESSO.ADMINISTRATIVO.CRota.ROTA oROTA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRota/IncluirPontoRota", ReplyAction="http://tempuri.org/ICRota/IncluirPontoRotaResponse")]
        void IncluirPontoRota(ACESSO.ADMINISTRATIVO.CRota.PONTOROTA oPontoRota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRota/ExcluirPontoRota", ReplyAction="http://tempuri.org/ICRota/ExcluirPontoRotaResponse")]
        void ExcluirPontoRota(ACESSO.ADMINISTRATIVO.CRota.PONTOROTA oPontoRota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRota/Alterar", ReplyAction="http://tempuri.org/ICRota/AlterarResponse")]
        void Alterar(ACESSO.ADMINISTRATIVO.CRota.ROTA oROTA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRota/Excluir", ReplyAction="http://tempuri.org/ICRota/ExcluirResponse")]
        void Excluir(ACESSO.ADMINISTRATIVO.CRota.ROTA oROTA);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRota/PontosRota", ReplyAction="http://tempuri.org/ICRota/PontosRotaResponse")]
        ACESSO.ADMINISTRATIVO.CRota.vw_PontoRota[] PontosRota(int PrCodigoRota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRota/OrdemMaisUm", ReplyAction="http://tempuri.org/ICRota/OrdemMaisUmResponse")]
        void OrdemMaisUm(int PRCodigoRota, int PRCodigoPontoControle, char PRTipoPontoControle);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICRota/OrdemMenosUm", ReplyAction="http://tempuri.org/ICRota/OrdemMenosUmResponse")]
        void OrdemMenosUm(int PRCodigoRota, int PRCodigoPontoControle, char PRTipoPontoControle);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICRotaChannel : ACESSO.ADMINISTRATIVO.CRota.ICRota, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CRotaClient : System.ServiceModel.ClientBase<ACESSO.ADMINISTRATIVO.CRota.ICRota>, ACESSO.ADMINISTRATIVO.CRota.ICRota {
        
        public CRotaClient() {
        }
        
        public CRotaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CRotaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRotaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CRotaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ACESSO.ADMINISTRATIVO.CRota.ROTA[] ListarTodasRotas() {
            return base.Channel.ListarTodasRotas();
        }
        
        public ACESSO.ADMINISTRATIVO.CRota.PONTOCONTROLE[] ListarPontosControleTipo(char TipoPonto) {
            return base.Channel.ListarPontosControleTipo(TipoPonto);
        }
        
        public ACESSO.ADMINISTRATIVO.CRota.ROTA SelecionaPKROTA(int Codigo) {
            return base.Channel.SelecionaPKROTA(Codigo);
        }
        
        public int Incluir(ACESSO.ADMINISTRATIVO.CRota.ROTA oROTA) {
            return base.Channel.Incluir(oROTA);
        }
        
        public void IncluirPontoRota(ACESSO.ADMINISTRATIVO.CRota.PONTOROTA oPontoRota) {
            base.Channel.IncluirPontoRota(oPontoRota);
        }
        
        public void ExcluirPontoRota(ACESSO.ADMINISTRATIVO.CRota.PONTOROTA oPontoRota) {
            base.Channel.ExcluirPontoRota(oPontoRota);
        }
        
        public void Alterar(ACESSO.ADMINISTRATIVO.CRota.ROTA oROTA) {
            base.Channel.Alterar(oROTA);
        }
        
        public void Excluir(ACESSO.ADMINISTRATIVO.CRota.ROTA oROTA) {
            base.Channel.Excluir(oROTA);
        }
        
        public ACESSO.ADMINISTRATIVO.CRota.vw_PontoRota[] PontosRota(int PrCodigoRota) {
            return base.Channel.PontosRota(PrCodigoRota);
        }
        
        public void OrdemMaisUm(int PRCodigoRota, int PRCodigoPontoControle, char PRTipoPontoControle) {
            base.Channel.OrdemMaisUm(PRCodigoRota, PRCodigoPontoControle, PRTipoPontoControle);
        }
        
        public void OrdemMenosUm(int PRCodigoRota, int PRCodigoPontoControle, char PRTipoPontoControle) {
            base.Channel.OrdemMenosUm(PRCodigoRota, PRCodigoPontoControle, PRTipoPontoControle);
        }
    }
}
