//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACESSO.ADMINISTRATIVO.CUsuario {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ROTAUSUARIO", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class ROTAUSUARIO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> RUBloqueadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RUCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RUCodigoRotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RUCodigoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RUDataExpiracaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RUDataInicioPermissaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RUMotivoBloqueioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> RUBloqueada {
            get {
                return this.RUBloqueadaField;
            }
            set {
                if ((this.RUBloqueadaField.Equals(value) != true)) {
                    this.RUBloqueadaField = value;
                    this.RaisePropertyChanged("RUBloqueada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RUCodigo {
            get {
                return this.RUCodigoField;
            }
            set {
                if ((this.RUCodigoField.Equals(value) != true)) {
                    this.RUCodigoField = value;
                    this.RaisePropertyChanged("RUCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RUCodigoRota {
            get {
                return this.RUCodigoRotaField;
            }
            set {
                if ((this.RUCodigoRotaField.Equals(value) != true)) {
                    this.RUCodigoRotaField = value;
                    this.RaisePropertyChanged("RUCodigoRota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RUCodigoUsuario {
            get {
                return this.RUCodigoUsuarioField;
            }
            set {
                if ((this.RUCodigoUsuarioField.Equals(value) != true)) {
                    this.RUCodigoUsuarioField = value;
                    this.RaisePropertyChanged("RUCodigoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RUDataExpiracao {
            get {
                return this.RUDataExpiracaoField;
            }
            set {
                if ((this.RUDataExpiracaoField.Equals(value) != true)) {
                    this.RUDataExpiracaoField = value;
                    this.RaisePropertyChanged("RUDataExpiracao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RUDataInicioPermissao {
            get {
                return this.RUDataInicioPermissaoField;
            }
            set {
                if ((this.RUDataInicioPermissaoField.Equals(value) != true)) {
                    this.RUDataInicioPermissaoField = value;
                    this.RaisePropertyChanged("RUDataInicioPermissao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RUMotivoBloqueio {
            get {
                return this.RUMotivoBloqueioField;
            }
            set {
                if ((object.ReferenceEquals(this.RUMotivoBloqueioField, value) != true)) {
                    this.RUMotivoBloqueioField = value;
                    this.RaisePropertyChanged("RUMotivoBloqueio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="USUARIO", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class USUARIO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> USAdministradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> USAuditorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool USBloqueadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int USCODIGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> USCODIGOESTAGIARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> USCODIGOTERCEIROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> USCODIGOVISITANTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> USGerenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> USMATFUNCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USMotivoBloqueioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> USSegurancaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USSenhaOpcionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char USTIPOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USUSUARIOREDEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> USAdministrador {
            get {
                return this.USAdministradorField;
            }
            set {
                if ((this.USAdministradorField.Equals(value) != true)) {
                    this.USAdministradorField = value;
                    this.RaisePropertyChanged("USAdministrador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> USAuditor {
            get {
                return this.USAuditorField;
            }
            set {
                if ((this.USAuditorField.Equals(value) != true)) {
                    this.USAuditorField = value;
                    this.RaisePropertyChanged("USAuditor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool USBloqueado {
            get {
                return this.USBloqueadoField;
            }
            set {
                if ((this.USBloqueadoField.Equals(value) != true)) {
                    this.USBloqueadoField = value;
                    this.RaisePropertyChanged("USBloqueado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int USCODIGO {
            get {
                return this.USCODIGOField;
            }
            set {
                if ((this.USCODIGOField.Equals(value) != true)) {
                    this.USCODIGOField = value;
                    this.RaisePropertyChanged("USCODIGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> USCODIGOESTAGIARIO {
            get {
                return this.USCODIGOESTAGIARIOField;
            }
            set {
                if ((this.USCODIGOESTAGIARIOField.Equals(value) != true)) {
                    this.USCODIGOESTAGIARIOField = value;
                    this.RaisePropertyChanged("USCODIGOESTAGIARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> USCODIGOTERCEIRO {
            get {
                return this.USCODIGOTERCEIROField;
            }
            set {
                if ((this.USCODIGOTERCEIROField.Equals(value) != true)) {
                    this.USCODIGOTERCEIROField = value;
                    this.RaisePropertyChanged("USCODIGOTERCEIRO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> USCODIGOVISITANTE {
            get {
                return this.USCODIGOVISITANTEField;
            }
            set {
                if ((this.USCODIGOVISITANTEField.Equals(value) != true)) {
                    this.USCODIGOVISITANTEField = value;
                    this.RaisePropertyChanged("USCODIGOVISITANTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> USGerente {
            get {
                return this.USGerenteField;
            }
            set {
                if ((this.USGerenteField.Equals(value) != true)) {
                    this.USGerenteField = value;
                    this.RaisePropertyChanged("USGerente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> USMATFUNC {
            get {
                return this.USMATFUNCField;
            }
            set {
                if ((this.USMATFUNCField.Equals(value) != true)) {
                    this.USMATFUNCField = value;
                    this.RaisePropertyChanged("USMATFUNC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USMotivoBloqueio {
            get {
                return this.USMotivoBloqueioField;
            }
            set {
                if ((object.ReferenceEquals(this.USMotivoBloqueioField, value) != true)) {
                    this.USMotivoBloqueioField = value;
                    this.RaisePropertyChanged("USMotivoBloqueio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> USSeguranca {
            get {
                return this.USSegurancaField;
            }
            set {
                if ((this.USSegurancaField.Equals(value) != true)) {
                    this.USSegurancaField = value;
                    this.RaisePropertyChanged("USSeguranca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USSenhaOpcional {
            get {
                return this.USSenhaOpcionalField;
            }
            set {
                if ((object.ReferenceEquals(this.USSenhaOpcionalField, value) != true)) {
                    this.USSenhaOpcionalField = value;
                    this.RaisePropertyChanged("USSenhaOpcional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char USTIPO {
            get {
                return this.USTIPOField;
            }
            set {
                if ((this.USTIPOField.Equals(value) != true)) {
                    this.USTIPOField = value;
                    this.RaisePropertyChanged("USTIPO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USUSUARIOREDE {
            get {
                return this.USUSUARIOREDEField;
            }
            set {
                if ((object.ReferenceEquals(this.USUSUARIOREDEField, value) != true)) {
                    this.USUSUARIOREDEField = value;
                    this.RaisePropertyChanged("USUSUARIOREDE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EQUIPUSUARIO", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class EQUIPUSUARIO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EUSCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EUSCodigoEquipamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EUSCodigoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EUSDataFimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EUSDataInicioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EUSCodigo {
            get {
                return this.EUSCodigoField;
            }
            set {
                if ((this.EUSCodigoField.Equals(value) != true)) {
                    this.EUSCodigoField = value;
                    this.RaisePropertyChanged("EUSCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EUSCodigoEquipamento {
            get {
                return this.EUSCodigoEquipamentoField;
            }
            set {
                if ((this.EUSCodigoEquipamentoField.Equals(value) != true)) {
                    this.EUSCodigoEquipamentoField = value;
                    this.RaisePropertyChanged("EUSCodigoEquipamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EUSCodigoUsuario {
            get {
                return this.EUSCodigoUsuarioField;
            }
            set {
                if ((this.EUSCodigoUsuarioField.Equals(value) != true)) {
                    this.EUSCodigoUsuarioField = value;
                    this.RaisePropertyChanged("EUSCodigoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EUSDataFim {
            get {
                return this.EUSDataFimField;
            }
            set {
                if ((this.EUSDataFimField.Equals(value) != true)) {
                    this.EUSDataFimField = value;
                    this.RaisePropertyChanged("EUSDataFim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EUSDataInicio {
            get {
                return this.EUSDataInicioField;
            }
            set {
                if ((this.EUSDataInicioField.Equals(value) != true)) {
                    this.EUSDataInicioField = value;
                    this.RaisePropertyChanged("EUSDataInicio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vw_EquipamentoUsuario", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class vw_EquipamentoUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EUSCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EUSCodigoEquipamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EUSCodigoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EUSDataFimField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> EUSDataInicioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EqNomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EqTAGRFIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EUSCodigo {
            get {
                return this.EUSCodigoField;
            }
            set {
                if ((this.EUSCodigoField.Equals(value) != true)) {
                    this.EUSCodigoField = value;
                    this.RaisePropertyChanged("EUSCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EUSCodigoEquipamento {
            get {
                return this.EUSCodigoEquipamentoField;
            }
            set {
                if ((this.EUSCodigoEquipamentoField.Equals(value) != true)) {
                    this.EUSCodigoEquipamentoField = value;
                    this.RaisePropertyChanged("EUSCodigoEquipamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EUSCodigoUsuario {
            get {
                return this.EUSCodigoUsuarioField;
            }
            set {
                if ((this.EUSCodigoUsuarioField.Equals(value) != true)) {
                    this.EUSCodigoUsuarioField = value;
                    this.RaisePropertyChanged("EUSCodigoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EUSDataFim {
            get {
                return this.EUSDataFimField;
            }
            set {
                if ((this.EUSDataFimField.Equals(value) != true)) {
                    this.EUSDataFimField = value;
                    this.RaisePropertyChanged("EUSDataFim");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> EUSDataInicio {
            get {
                return this.EUSDataInicioField;
            }
            set {
                if ((this.EUSDataInicioField.Equals(value) != true)) {
                    this.EUSDataInicioField = value;
                    this.RaisePropertyChanged("EUSDataInicio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EqNome {
            get {
                return this.EqNomeField;
            }
            set {
                if ((object.ReferenceEquals(this.EqNomeField, value) != true)) {
                    this.EqNomeField = value;
                    this.RaisePropertyChanged("EqNome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EqTAGRFID {
            get {
                return this.EqTAGRFIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EqTAGRFIDField, value) != true)) {
                    this.EqTAGRFIDField = value;
                    this.RaisePropertyChanged("EqTAGRFID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EQUIPAMENTO", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class EQUIPAMENTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> EqBloqueadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EqCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EqNomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EqTAGRFIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EqTempoSinalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EqTipoEquipamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char EqTipoLiberaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FaCodigoFabricanteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> EqBloqueado {
            get {
                return this.EqBloqueadoField;
            }
            set {
                if ((this.EqBloqueadoField.Equals(value) != true)) {
                    this.EqBloqueadoField = value;
                    this.RaisePropertyChanged("EqBloqueado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EqCodigo {
            get {
                return this.EqCodigoField;
            }
            set {
                if ((this.EqCodigoField.Equals(value) != true)) {
                    this.EqCodigoField = value;
                    this.RaisePropertyChanged("EqCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EqNome {
            get {
                return this.EqNomeField;
            }
            set {
                if ((object.ReferenceEquals(this.EqNomeField, value) != true)) {
                    this.EqNomeField = value;
                    this.RaisePropertyChanged("EqNome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EqTAGRFID {
            get {
                return this.EqTAGRFIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EqTAGRFIDField, value) != true)) {
                    this.EqTAGRFIDField = value;
                    this.RaisePropertyChanged("EqTAGRFID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EqTempoSinal {
            get {
                return this.EqTempoSinalField;
            }
            set {
                if ((this.EqTempoSinalField.Equals(value) != true)) {
                    this.EqTempoSinalField = value;
                    this.RaisePropertyChanged("EqTempoSinal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EqTipoEquipamento {
            get {
                return this.EqTipoEquipamentoField;
            }
            set {
                if ((this.EqTipoEquipamentoField.Equals(value) != true)) {
                    this.EqTipoEquipamentoField = value;
                    this.RaisePropertyChanged("EqTipoEquipamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char EqTipoLibera {
            get {
                return this.EqTipoLiberaField;
            }
            set {
                if ((this.EqTipoLiberaField.Equals(value) != true)) {
                    this.EqTipoLiberaField = value;
                    this.RaisePropertyChanged("EqTipoLibera");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FaCodigoFabricante {
            get {
                return this.FaCodigoFabricanteField;
            }
            set {
                if ((this.FaCodigoFabricanteField.Equals(value) != true)) {
                    this.FaCodigoFabricanteField = value;
                    this.RaisePropertyChanged("FaCodigoFabricante");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CARTAO", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class CARTAO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> CrBloqueadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CrCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CrCodigoFabricanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CrDataBloqueioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CrMotivoBloqueioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CrNumeroCartaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char CrTipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> CrBloqueado {
            get {
                return this.CrBloqueadoField;
            }
            set {
                if ((this.CrBloqueadoField.Equals(value) != true)) {
                    this.CrBloqueadoField = value;
                    this.RaisePropertyChanged("CrBloqueado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CrCodigo {
            get {
                return this.CrCodigoField;
            }
            set {
                if ((this.CrCodigoField.Equals(value) != true)) {
                    this.CrCodigoField = value;
                    this.RaisePropertyChanged("CrCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CrCodigoFabricante {
            get {
                return this.CrCodigoFabricanteField;
            }
            set {
                if ((this.CrCodigoFabricanteField.Equals(value) != true)) {
                    this.CrCodigoFabricanteField = value;
                    this.RaisePropertyChanged("CrCodigoFabricante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CrDataBloqueio {
            get {
                return this.CrDataBloqueioField;
            }
            set {
                if ((this.CrDataBloqueioField.Equals(value) != true)) {
                    this.CrDataBloqueioField = value;
                    this.RaisePropertyChanged("CrDataBloqueio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CrMotivoBloqueio {
            get {
                return this.CrMotivoBloqueioField;
            }
            set {
                if ((object.ReferenceEquals(this.CrMotivoBloqueioField, value) != true)) {
                    this.CrMotivoBloqueioField = value;
                    this.RaisePropertyChanged("CrMotivoBloqueio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CrNumeroCartao {
            get {
                return this.CrNumeroCartaoField;
            }
            set {
                if ((object.ReferenceEquals(this.CrNumeroCartaoField, value) != true)) {
                    this.CrNumeroCartaoField = value;
                    this.RaisePropertyChanged("CrNumeroCartao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char CrTipo {
            get {
                return this.CrTipoField;
            }
            set {
                if ((this.CrTipoField.Equals(value) != true)) {
                    this.CrTipoField = value;
                    this.RaisePropertyChanged("CrTipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ROTA", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class ROTA : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> ROBloqueadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ROCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RODescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ROMotivoBloqueioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RONomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> ROBloqueada {
            get {
                return this.ROBloqueadaField;
            }
            set {
                if ((this.ROBloqueadaField.Equals(value) != true)) {
                    this.ROBloqueadaField = value;
                    this.RaisePropertyChanged("ROBloqueada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ROCodigo {
            get {
                return this.ROCodigoField;
            }
            set {
                if ((this.ROCodigoField.Equals(value) != true)) {
                    this.ROCodigoField = value;
                    this.RaisePropertyChanged("ROCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RODescricao {
            get {
                return this.RODescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.RODescricaoField, value) != true)) {
                    this.RODescricaoField = value;
                    this.RaisePropertyChanged("RODescricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ROMotivoBloqueio {
            get {
                return this.ROMotivoBloqueioField;
            }
            set {
                if ((object.ReferenceEquals(this.ROMotivoBloqueioField, value) != true)) {
                    this.ROMotivoBloqueioField = value;
                    this.RaisePropertyChanged("ROMotivoBloqueio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RONome {
            get {
                return this.RONomeField;
            }
            set {
                if ((object.ReferenceEquals(this.RONomeField, value) != true)) {
                    this.RONomeField = value;
                    this.RaisePropertyChanged("RONome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FUNCIONARIO", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class FUNCIONARIO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FUCodigoLocalidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FUCodigoLotacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FUMATFUNCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FUNOMFUNCField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FUCodigoLocalidade {
            get {
                return this.FUCodigoLocalidadeField;
            }
            set {
                if ((this.FUCodigoLocalidadeField.Equals(value) != true)) {
                    this.FUCodigoLocalidadeField = value;
                    this.RaisePropertyChanged("FUCodigoLocalidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FUCodigoLotacao {
            get {
                return this.FUCodigoLotacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.FUCodigoLotacaoField, value) != true)) {
                    this.FUCodigoLotacaoField = value;
                    this.RaisePropertyChanged("FUCodigoLotacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FUMATFUNC {
            get {
                return this.FUMATFUNCField;
            }
            set {
                if ((this.FUMATFUNCField.Equals(value) != true)) {
                    this.FUMATFUNCField = value;
                    this.RaisePropertyChanged("FUMATFUNC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FUNOMFUNC {
            get {
                return this.FUNOMFUNCField;
            }
            set {
                if ((object.ReferenceEquals(this.FUNOMFUNCField, value) != true)) {
                    this.FUNOMFUNCField = value;
                    this.RaisePropertyChanged("FUNOMFUNC");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TERCEIRO", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class TERCEIRO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TeCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeNomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeCodigo {
            get {
                return this.TeCodigoField;
            }
            set {
                if ((this.TeCodigoField.Equals(value) != true)) {
                    this.TeCodigoField = value;
                    this.RaisePropertyChanged("TeCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeNome {
            get {
                return this.TeNomeField;
            }
            set {
                if ((object.ReferenceEquals(this.TeNomeField, value) != true)) {
                    this.TeNomeField = value;
                    this.RaisePropertyChanged("TeNome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ESTAGIARIO", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class ESTAGIARIO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ESCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ESCodigoLocalidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESCodigoLotacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESNomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ESCodigo {
            get {
                return this.ESCodigoField;
            }
            set {
                if ((this.ESCodigoField.Equals(value) != true)) {
                    this.ESCodigoField = value;
                    this.RaisePropertyChanged("ESCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ESCodigoLocalidade {
            get {
                return this.ESCodigoLocalidadeField;
            }
            set {
                if ((this.ESCodigoLocalidadeField.Equals(value) != true)) {
                    this.ESCodigoLocalidadeField = value;
                    this.RaisePropertyChanged("ESCodigoLocalidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ESCodigoLotacao {
            get {
                return this.ESCodigoLotacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.ESCodigoLotacaoField, value) != true)) {
                    this.ESCodigoLotacaoField = value;
                    this.RaisePropertyChanged("ESCodigoLotacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ESNome {
            get {
                return this.ESNomeField;
            }
            set {
                if ((object.ReferenceEquals(this.ESNomeField, value) != true)) {
                    this.ESNomeField = value;
                    this.RaisePropertyChanged("ESNome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VISITANTE", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class VISITANTE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ViCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ViNomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ViCodigo {
            get {
                return this.ViCodigoField;
            }
            set {
                if ((this.ViCodigoField.Equals(value) != true)) {
                    this.ViCodigoField = value;
                    this.RaisePropertyChanged("ViCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ViNome {
            get {
                return this.ViNomeField;
            }
            set {
                if ((object.ReferenceEquals(this.ViNomeField, value) != true)) {
                    this.ViNomeField = value;
                    this.RaisePropertyChanged("ViNome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vw_RotaUsuario", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class vw_RotaUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RONomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> RUBloqueadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RUCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RUCodigoRotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RUCodigoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RUDataExpiracaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RUDataInicioPermissaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RUMotivoBloqueioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RONome {
            get {
                return this.RONomeField;
            }
            set {
                if ((object.ReferenceEquals(this.RONomeField, value) != true)) {
                    this.RONomeField = value;
                    this.RaisePropertyChanged("RONome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> RUBloqueada {
            get {
                return this.RUBloqueadaField;
            }
            set {
                if ((this.RUBloqueadaField.Equals(value) != true)) {
                    this.RUBloqueadaField = value;
                    this.RaisePropertyChanged("RUBloqueada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RUCodigo {
            get {
                return this.RUCodigoField;
            }
            set {
                if ((this.RUCodigoField.Equals(value) != true)) {
                    this.RUCodigoField = value;
                    this.RaisePropertyChanged("RUCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RUCodigoRota {
            get {
                return this.RUCodigoRotaField;
            }
            set {
                if ((this.RUCodigoRotaField.Equals(value) != true)) {
                    this.RUCodigoRotaField = value;
                    this.RaisePropertyChanged("RUCodigoRota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RUCodigoUsuario {
            get {
                return this.RUCodigoUsuarioField;
            }
            set {
                if ((this.RUCodigoUsuarioField.Equals(value) != true)) {
                    this.RUCodigoUsuarioField = value;
                    this.RaisePropertyChanged("RUCodigoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RUDataExpiracao {
            get {
                return this.RUDataExpiracaoField;
            }
            set {
                if ((this.RUDataExpiracaoField.Equals(value) != true)) {
                    this.RUDataExpiracaoField = value;
                    this.RaisePropertyChanged("RUDataExpiracao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RUDataInicioPermissao {
            get {
                return this.RUDataInicioPermissaoField;
            }
            set {
                if ((this.RUDataInicioPermissaoField.Equals(value) != true)) {
                    this.RUDataInicioPermissaoField = value;
                    this.RaisePropertyChanged("RUDataInicioPermissao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RUMotivoBloqueio {
            get {
                return this.RUMotivoBloqueioField;
            }
            set {
                if ((object.ReferenceEquals(this.RUMotivoBloqueioField, value) != true)) {
                    this.RUMotivoBloqueioField = value;
                    this.RaisePropertyChanged("RUMotivoBloqueio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vw_CartaoUsuario", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class vw_CartaoUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CSCODIGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CSCodigoCartaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CSCodigoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CSDataDevolucaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CSDataEntregaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CSDataExpiracaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> CSDevolvidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CSObservacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CrNumeroCartaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char CrTipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CSCODIGO {
            get {
                return this.CSCODIGOField;
            }
            set {
                if ((this.CSCODIGOField.Equals(value) != true)) {
                    this.CSCODIGOField = value;
                    this.RaisePropertyChanged("CSCODIGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CSCodigoCartao {
            get {
                return this.CSCodigoCartaoField;
            }
            set {
                if ((this.CSCodigoCartaoField.Equals(value) != true)) {
                    this.CSCodigoCartaoField = value;
                    this.RaisePropertyChanged("CSCodigoCartao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CSCodigoUsuario {
            get {
                return this.CSCodigoUsuarioField;
            }
            set {
                if ((this.CSCodigoUsuarioField.Equals(value) != true)) {
                    this.CSCodigoUsuarioField = value;
                    this.RaisePropertyChanged("CSCodigoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CSDataDevolucao {
            get {
                return this.CSDataDevolucaoField;
            }
            set {
                if ((this.CSDataDevolucaoField.Equals(value) != true)) {
                    this.CSDataDevolucaoField = value;
                    this.RaisePropertyChanged("CSDataDevolucao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CSDataEntrega {
            get {
                return this.CSDataEntregaField;
            }
            set {
                if ((this.CSDataEntregaField.Equals(value) != true)) {
                    this.CSDataEntregaField = value;
                    this.RaisePropertyChanged("CSDataEntrega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CSDataExpiracao {
            get {
                return this.CSDataExpiracaoField;
            }
            set {
                if ((this.CSDataExpiracaoField.Equals(value) != true)) {
                    this.CSDataExpiracaoField = value;
                    this.RaisePropertyChanged("CSDataExpiracao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> CSDevolvido {
            get {
                return this.CSDevolvidoField;
            }
            set {
                if ((this.CSDevolvidoField.Equals(value) != true)) {
                    this.CSDevolvidoField = value;
                    this.RaisePropertyChanged("CSDevolvido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CSObservacao {
            get {
                return this.CSObservacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.CSObservacaoField, value) != true)) {
                    this.CSObservacaoField = value;
                    this.RaisePropertyChanged("CSObservacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CrNumeroCartao {
            get {
                return this.CrNumeroCartaoField;
            }
            set {
                if ((object.ReferenceEquals(this.CrNumeroCartaoField, value) != true)) {
                    this.CrNumeroCartaoField = value;
                    this.RaisePropertyChanged("CrNumeroCartao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char CrTipo {
            get {
                return this.CrTipoField;
            }
            set {
                if ((this.CrTipoField.Equals(value) != true)) {
                    this.CrTipoField = value;
                    this.RaisePropertyChanged("CrTipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vw_Digital", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class vw_Digital : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DiCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DiDataVencimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char DiDedoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ACESSO.ADMINISTRATIVO.CUsuario.Binary DiImgDigitalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char DiMaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EqNomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HaCodigoUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DiCodigo {
            get {
                return this.DiCodigoField;
            }
            set {
                if ((this.DiCodigoField.Equals(value) != true)) {
                    this.DiCodigoField = value;
                    this.RaisePropertyChanged("DiCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DiDataVencimento {
            get {
                return this.DiDataVencimentoField;
            }
            set {
                if ((this.DiDataVencimentoField.Equals(value) != true)) {
                    this.DiDataVencimentoField = value;
                    this.RaisePropertyChanged("DiDataVencimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char DiDedo {
            get {
                return this.DiDedoField;
            }
            set {
                if ((this.DiDedoField.Equals(value) != true)) {
                    this.DiDedoField = value;
                    this.RaisePropertyChanged("DiDedo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ACESSO.ADMINISTRATIVO.CUsuario.Binary DiImgDigital {
            get {
                return this.DiImgDigitalField;
            }
            set {
                if ((object.ReferenceEquals(this.DiImgDigitalField, value) != true)) {
                    this.DiImgDigitalField = value;
                    this.RaisePropertyChanged("DiImgDigital");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char DiMao {
            get {
                return this.DiMaoField;
            }
            set {
                if ((this.DiMaoField.Equals(value) != true)) {
                    this.DiMaoField = value;
                    this.RaisePropertyChanged("DiMao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EqNome {
            get {
                return this.EqNomeField;
            }
            set {
                if ((object.ReferenceEquals(this.EqNomeField, value) != true)) {
                    this.EqNomeField = value;
                    this.RaisePropertyChanged("EqNome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HaCodigoUsuario {
            get {
                return this.HaCodigoUsuarioField;
            }
            set {
                if ((this.HaCodigoUsuarioField.Equals(value) != true)) {
                    this.HaCodigoUsuarioField = value;
                    this.RaisePropertyChanged("HaCodigoUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Binary", Namespace="http://schemas.datacontract.org/2004/07/System.Data.Linq")]
    [System.SerializableAttribute()]
    public partial class Binary : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] BytesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Bytes {
            get {
                return this.BytesField;
            }
            set {
                if ((object.ReferenceEquals(this.BytesField, value) != true)) {
                    this.BytesField = value;
                    this.RaisePropertyChanged("Bytes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CARTAOUSUARIO", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class CARTAOUSUARIO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CSCODIGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CSCodigoCartaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CSCodigoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CSDataDevolucaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CSDataEntregaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CSDataExpiracaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> CSDevolvidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CSObservacaoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CSCODIGO {
            get {
                return this.CSCODIGOField;
            }
            set {
                if ((this.CSCODIGOField.Equals(value) != true)) {
                    this.CSCODIGOField = value;
                    this.RaisePropertyChanged("CSCODIGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CSCodigoCartao {
            get {
                return this.CSCodigoCartaoField;
            }
            set {
                if ((this.CSCodigoCartaoField.Equals(value) != true)) {
                    this.CSCodigoCartaoField = value;
                    this.RaisePropertyChanged("CSCodigoCartao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CSCodigoUsuario {
            get {
                return this.CSCodigoUsuarioField;
            }
            set {
                if ((this.CSCodigoUsuarioField.Equals(value) != true)) {
                    this.CSCodigoUsuarioField = value;
                    this.RaisePropertyChanged("CSCodigoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CSDataDevolucao {
            get {
                return this.CSDataDevolucaoField;
            }
            set {
                if ((this.CSDataDevolucaoField.Equals(value) != true)) {
                    this.CSDataDevolucaoField = value;
                    this.RaisePropertyChanged("CSDataDevolucao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CSDataEntrega {
            get {
                return this.CSDataEntregaField;
            }
            set {
                if ((this.CSDataEntregaField.Equals(value) != true)) {
                    this.CSDataEntregaField = value;
                    this.RaisePropertyChanged("CSDataEntrega");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CSDataExpiracao {
            get {
                return this.CSDataExpiracaoField;
            }
            set {
                if ((this.CSDataExpiracaoField.Equals(value) != true)) {
                    this.CSDataExpiracaoField = value;
                    this.RaisePropertyChanged("CSDataExpiracao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> CSDevolvido {
            get {
                return this.CSDevolvidoField;
            }
            set {
                if ((this.CSDevolvidoField.Equals(value) != true)) {
                    this.CSDevolvidoField = value;
                    this.RaisePropertyChanged("CSDevolvido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CSObservacao {
            get {
                return this.CSObservacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.CSObservacaoField, value) != true)) {
                    this.CSObservacaoField = value;
                    this.RaisePropertyChanged("CSObservacao");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CUsuario.ICUsuario")]
    public interface ICUsuario {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUsuario/ExcluirRotaUsuario", ReplyAction="http://tempuri.org/ICUsuario/ExcluirRotaUsuarioResponse")]
        void ExcluirRotaUsuario(ACESSO.ADMINISTRATIVO.CUsuario.ROTAUSUARIO oRota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUsuario/ExcluirDigital", ReplyAction="http://tempuri.org/ICUsuario/ExcluirDigitalResponse")]
        void ExcluirDigital(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUsuario/Alterar", ReplyAction="http://tempuri.org/ICUsuario/AlterarResponse")]
        void Alterar(ACESSO.ADMINISTRATIVO.CUsuario.USUARIO oUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUsuario/Excluir", ReplyAction="http://tempuri.org/ICUsuario/ExcluirResponse")]
        void Excluir(ACESSO.ADMINISTRATIVO.CUsuario.USUARIO oUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUsuario/CartaoAdicionado", ReplyAction="http://tempuri.org/ICUsuario/CartaoAdicionadoResponse")]
        bool CartaoAdicionado(int USCodigo, int CrCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUsuario/RotaAdicionada", ReplyAction="http://tempuri.org/ICUsuario/RotaAdicionadaResponse")]
        bool RotaAdicionada(int RUCodigoRota, int RUCodigoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUsuario/IncluirEquipamento", ReplyAction="http://tempuri.org/ICUsuario/IncluirEquipamentoResponse")]
        void IncluirEquipamento(ACESSO.ADMINISTRATIVO.CUsuario.EQUIPUSUARIO oEQUIPUSUARIO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUsuario/AlterarEquipamento", ReplyAction="http://tempuri.org/ICUsuario/AlterarEquipamentoResponse")]
        void AlterarEquipamento(ACESSO.ADMINISTRATIVO.CUsuario.EQUIPUSUARIO oEQUIPUSUARIO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUsuario/ExcluirEquipamento", ReplyAction="http://tempuri.org/ICUsuario/ExcluirEquipamentoResponse")]
        void ExcluirEquipamento(int pEUSCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUsuario/oListaEquipamentoUsuario", ReplyAction="http://tempuri.org/ICUsuario/oListaEquipamentoUsuarioResponse")]
        ACESSO.ADMINISTRATIVO.CUsuario.vw_EquipamentoUsuario[] oListaEquipamentoUsuario(int CodigoUSuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUsuario/ListarTodosEquipamentosNaoDistribuidos", ReplyAction="http://tempuri.org/ICUsuario/ListarTodosEquipamentosNaoDistribuidosResponse")]
        ACESSO.ADMINISTRATIVO.CUsuario.EQUIPAMENTO[] ListarTodosEquipamentosNaoDistribuidos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUsuario/ListarCartao", ReplyAction="http://tempuri.org/ICUsuario/ListarCartaoResponse")]
        ACESSO.ADMINISTRATIVO.CUsuario.CARTAO[] ListarCartao(char Tipo, int Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUsuario/ListarUsuario", ReplyAction="http://tempuri.org/ICUsuario/ListarUsuarioResponse")]
        ACESSO.ADMINISTRATIVO.CUsuario.USUARIO[] ListarUsuario(char Tipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUsuario/ListarRota", ReplyAction="http://tempuri.org/ICUsuario/ListarRotaResponse")]
        ACESSO.ADMINISTRATIVO.CUsuario.ROTA[] ListarRota();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUsuario/ListarFuncionario", ReplyAction="http://tempuri.org/ICUsuario/ListarFuncionarioResponse")]
        ACESSO.ADMINISTRATIVO.CUsuario.FUNCIONARIO[] ListarFuncionario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUsuario/ListarTerceiro", ReplyAction="http://tempuri.org/ICUsuario/ListarTerceiroResponse")]
        ACESSO.ADMINISTRATIVO.CUsuario.TERCEIRO[] ListarTerceiro();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUsuario/ListarEstagiario", ReplyAction="http://tempuri.org/ICUsuario/ListarEstagiarioResponse")]
        ACESSO.ADMINISTRATIVO.CUsuario.ESTAGIARIO[] ListarEstagiario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUsuario/ListarVisitante", ReplyAction="http://tempuri.org/ICUsuario/ListarVisitanteResponse")]
        ACESSO.ADMINISTRATIVO.CUsuario.VISITANTE[] ListarVisitante();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUsuario/ListarEquipamento", ReplyAction="http://tempuri.org/ICUsuario/ListarEquipamentoResponse")]
        ACESSO.ADMINISTRATIVO.CUsuario.EQUIPAMENTO[] ListarEquipamento();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUsuario/ListarRotaUsuario", ReplyAction="http://tempuri.org/ICUsuario/ListarRotaUsuarioResponse")]
        ACESSO.ADMINISTRATIVO.CUsuario.vw_RotaUsuario[] ListarRotaUsuario(char Tipo, int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUsuario/ListarCartaoUsuario", ReplyAction="http://tempuri.org/ICUsuario/ListarCartaoUsuarioResponse")]
        ACESSO.ADMINISTRATIVO.CUsuario.vw_CartaoUsuario[] ListarCartaoUsuario(char Tipo, int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUsuario/ListarDigitalUsuario", ReplyAction="http://tempuri.org/ICUsuario/ListarDigitalUsuarioResponse")]
        ACESSO.ADMINISTRATIVO.CUsuario.vw_Digital[] ListarDigitalUsuario(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUsuario/SelecionaEquipamentoUsuario", ReplyAction="http://tempuri.org/ICUsuario/SelecionaEquipamentoUsuarioResponse")]
        ACESSO.ADMINISTRATIVO.CUsuario.EQUIPUSUARIO SelecionaEquipamentoUsuario(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUsuario/SelecionaCartao", ReplyAction="http://tempuri.org/ICUsuario/SelecionaCartaoResponse")]
        ACESSO.ADMINISTRATIVO.CUsuario.CARTAO SelecionaCartao(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUsuario/SelecionaUsuario", ReplyAction="http://tempuri.org/ICUsuario/SelecionaUsuarioResponse")]
        ACESSO.ADMINISTRATIVO.CUsuario.USUARIO SelecionaUsuario(char Tipo, int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUsuario/SelecionaCartaoUSuarioPK", ReplyAction="http://tempuri.org/ICUsuario/SelecionaCartaoUSuarioPKResponse")]
        ACESSO.ADMINISTRATIVO.CUsuario.CARTAOUSUARIO SelecionaCartaoUSuarioPK(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUsuario/SelecionaRotaPK", ReplyAction="http://tempuri.org/ICUsuario/SelecionaRotaPKResponse")]
        ACESSO.ADMINISTRATIVO.CUsuario.ROTAUSUARIO SelecionaRotaPK(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUsuario/SelecionaFuncionario", ReplyAction="http://tempuri.org/ICUsuario/SelecionaFuncionarioResponse")]
        ACESSO.ADMINISTRATIVO.CUsuario.FUNCIONARIO SelecionaFuncionario(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUsuario/SelecionaEstagiario", ReplyAction="http://tempuri.org/ICUsuario/SelecionaEstagiarioResponse")]
        ACESSO.ADMINISTRATIVO.CUsuario.ESTAGIARIO SelecionaEstagiario(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUsuario/SelecionaVisitante", ReplyAction="http://tempuri.org/ICUsuario/SelecionaVisitanteResponse")]
        ACESSO.ADMINISTRATIVO.CUsuario.VISITANTE SelecionaVisitante(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUsuario/SelecionaTerceiro", ReplyAction="http://tempuri.org/ICUsuario/SelecionaTerceiroResponse")]
        ACESSO.ADMINISTRATIVO.CUsuario.TERCEIRO SelecionaTerceiro(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUsuario/Incluir", ReplyAction="http://tempuri.org/ICUsuario/IncluirResponse")]
        int Incluir(ACESSO.ADMINISTRATIVO.CUsuario.USUARIO oUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUsuario/IncluirCartaoUsuario", ReplyAction="http://tempuri.org/ICUsuario/IncluirCartaoUsuarioResponse")]
        void IncluirCartaoUsuario(ACESSO.ADMINISTRATIVO.CUsuario.CARTAOUSUARIO oCartao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUsuario/AlterarCartaoUsuario", ReplyAction="http://tempuri.org/ICUsuario/AlterarCartaoUsuarioResponse")]
        void AlterarCartaoUsuario(ACESSO.ADMINISTRATIVO.CUsuario.CARTAOUSUARIO oCartao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUsuario/ExcluirCartaoUsuario", ReplyAction="http://tempuri.org/ICUsuario/ExcluirCartaoUsuarioResponse")]
        void ExcluirCartaoUsuario(ACESSO.ADMINISTRATIVO.CUsuario.CARTAOUSUARIO oCartao);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUsuario/IncluirRotaUsuario", ReplyAction="http://tempuri.org/ICUsuario/IncluirRotaUsuarioResponse")]
        void IncluirRotaUsuario(ACESSO.ADMINISTRATIVO.CUsuario.ROTAUSUARIO oRota);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICUsuario/AlterarRotaUsuario", ReplyAction="http://tempuri.org/ICUsuario/AlterarRotaUsuarioResponse")]
        void AlterarRotaUsuario(ACESSO.ADMINISTRATIVO.CUsuario.ROTAUSUARIO oRota);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICUsuarioChannel : ACESSO.ADMINISTRATIVO.CUsuario.ICUsuario, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CUsuarioClient : System.ServiceModel.ClientBase<ACESSO.ADMINISTRATIVO.CUsuario.ICUsuario>, ACESSO.ADMINISTRATIVO.CUsuario.ICUsuario {
        
        public CUsuarioClient() {
        }
        
        public CUsuarioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CUsuarioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CUsuarioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CUsuarioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void ExcluirRotaUsuario(ACESSO.ADMINISTRATIVO.CUsuario.ROTAUSUARIO oRota) {
            base.Channel.ExcluirRotaUsuario(oRota);
        }
        
        public void ExcluirDigital(int Codigo) {
            base.Channel.ExcluirDigital(Codigo);
        }
        
        public void Alterar(ACESSO.ADMINISTRATIVO.CUsuario.USUARIO oUsuario) {
            base.Channel.Alterar(oUsuario);
        }
        
        public void Excluir(ACESSO.ADMINISTRATIVO.CUsuario.USUARIO oUsuario) {
            base.Channel.Excluir(oUsuario);
        }
        
        public bool CartaoAdicionado(int USCodigo, int CrCodigo) {
            return base.Channel.CartaoAdicionado(USCodigo, CrCodigo);
        }
        
        public bool RotaAdicionada(int RUCodigoRota, int RUCodigoUsuario) {
            return base.Channel.RotaAdicionada(RUCodigoRota, RUCodigoUsuario);
        }
        
        public void IncluirEquipamento(ACESSO.ADMINISTRATIVO.CUsuario.EQUIPUSUARIO oEQUIPUSUARIO) {
            base.Channel.IncluirEquipamento(oEQUIPUSUARIO);
        }
        
        public void AlterarEquipamento(ACESSO.ADMINISTRATIVO.CUsuario.EQUIPUSUARIO oEQUIPUSUARIO) {
            base.Channel.AlterarEquipamento(oEQUIPUSUARIO);
        }
        
        public void ExcluirEquipamento(int pEUSCodigo) {
            base.Channel.ExcluirEquipamento(pEUSCodigo);
        }
        
        public ACESSO.ADMINISTRATIVO.CUsuario.vw_EquipamentoUsuario[] oListaEquipamentoUsuario(int CodigoUSuario) {
            return base.Channel.oListaEquipamentoUsuario(CodigoUSuario);
        }
        
        public ACESSO.ADMINISTRATIVO.CUsuario.EQUIPAMENTO[] ListarTodosEquipamentosNaoDistribuidos() {
            return base.Channel.ListarTodosEquipamentosNaoDistribuidos();
        }
        
        public ACESSO.ADMINISTRATIVO.CUsuario.CARTAO[] ListarCartao(char Tipo, int Usuario) {
            return base.Channel.ListarCartao(Tipo, Usuario);
        }
        
        public ACESSO.ADMINISTRATIVO.CUsuario.USUARIO[] ListarUsuario(char Tipo) {
            return base.Channel.ListarUsuario(Tipo);
        }
        
        public ACESSO.ADMINISTRATIVO.CUsuario.ROTA[] ListarRota() {
            return base.Channel.ListarRota();
        }
        
        public ACESSO.ADMINISTRATIVO.CUsuario.FUNCIONARIO[] ListarFuncionario() {
            return base.Channel.ListarFuncionario();
        }
        
        public ACESSO.ADMINISTRATIVO.CUsuario.TERCEIRO[] ListarTerceiro() {
            return base.Channel.ListarTerceiro();
        }
        
        public ACESSO.ADMINISTRATIVO.CUsuario.ESTAGIARIO[] ListarEstagiario() {
            return base.Channel.ListarEstagiario();
        }
        
        public ACESSO.ADMINISTRATIVO.CUsuario.VISITANTE[] ListarVisitante() {
            return base.Channel.ListarVisitante();
        }
        
        public ACESSO.ADMINISTRATIVO.CUsuario.EQUIPAMENTO[] ListarEquipamento() {
            return base.Channel.ListarEquipamento();
        }
        
        public ACESSO.ADMINISTRATIVO.CUsuario.vw_RotaUsuario[] ListarRotaUsuario(char Tipo, int Codigo) {
            return base.Channel.ListarRotaUsuario(Tipo, Codigo);
        }
        
        public ACESSO.ADMINISTRATIVO.CUsuario.vw_CartaoUsuario[] ListarCartaoUsuario(char Tipo, int Codigo) {
            return base.Channel.ListarCartaoUsuario(Tipo, Codigo);
        }
        
        public ACESSO.ADMINISTRATIVO.CUsuario.vw_Digital[] ListarDigitalUsuario(int Codigo) {
            return base.Channel.ListarDigitalUsuario(Codigo);
        }
        
        public ACESSO.ADMINISTRATIVO.CUsuario.EQUIPUSUARIO SelecionaEquipamentoUsuario(int Codigo) {
            return base.Channel.SelecionaEquipamentoUsuario(Codigo);
        }
        
        public ACESSO.ADMINISTRATIVO.CUsuario.CARTAO SelecionaCartao(int Codigo) {
            return base.Channel.SelecionaCartao(Codigo);
        }
        
        public ACESSO.ADMINISTRATIVO.CUsuario.USUARIO SelecionaUsuario(char Tipo, int Codigo) {
            return base.Channel.SelecionaUsuario(Tipo, Codigo);
        }
        
        public ACESSO.ADMINISTRATIVO.CUsuario.CARTAOUSUARIO SelecionaCartaoUSuarioPK(int Codigo) {
            return base.Channel.SelecionaCartaoUSuarioPK(Codigo);
        }
        
        public ACESSO.ADMINISTRATIVO.CUsuario.ROTAUSUARIO SelecionaRotaPK(int Codigo) {
            return base.Channel.SelecionaRotaPK(Codigo);
        }
        
        public ACESSO.ADMINISTRATIVO.CUsuario.FUNCIONARIO SelecionaFuncionario(int Codigo) {
            return base.Channel.SelecionaFuncionario(Codigo);
        }
        
        public ACESSO.ADMINISTRATIVO.CUsuario.ESTAGIARIO SelecionaEstagiario(int Codigo) {
            return base.Channel.SelecionaEstagiario(Codigo);
        }
        
        public ACESSO.ADMINISTRATIVO.CUsuario.VISITANTE SelecionaVisitante(int Codigo) {
            return base.Channel.SelecionaVisitante(Codigo);
        }
        
        public ACESSO.ADMINISTRATIVO.CUsuario.TERCEIRO SelecionaTerceiro(int Codigo) {
            return base.Channel.SelecionaTerceiro(Codigo);
        }
        
        public int Incluir(ACESSO.ADMINISTRATIVO.CUsuario.USUARIO oUsuario) {
            return base.Channel.Incluir(oUsuario);
        }
        
        public void IncluirCartaoUsuario(ACESSO.ADMINISTRATIVO.CUsuario.CARTAOUSUARIO oCartao) {
            base.Channel.IncluirCartaoUsuario(oCartao);
        }
        
        public void AlterarCartaoUsuario(ACESSO.ADMINISTRATIVO.CUsuario.CARTAOUSUARIO oCartao) {
            base.Channel.AlterarCartaoUsuario(oCartao);
        }
        
        public void ExcluirCartaoUsuario(ACESSO.ADMINISTRATIVO.CUsuario.CARTAOUSUARIO oCartao) {
            base.Channel.ExcluirCartaoUsuario(oCartao);
        }
        
        public void IncluirRotaUsuario(ACESSO.ADMINISTRATIVO.CUsuario.ROTAUSUARIO oRota) {
            base.Channel.IncluirRotaUsuario(oRota);
        }
        
        public void AlterarRotaUsuario(ACESSO.ADMINISTRATIVO.CUsuario.ROTAUSUARIO oRota) {
            base.Channel.AlterarRotaUsuario(oRota);
        }
    }
}
