//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACESSO.AUDITORIA.CFiltro {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="USUARIO", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class USUARIO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> USAdministradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> USAuditorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool USBloqueadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int USCODIGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> USCODIGOESTAGIARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> USCODIGOTERCEIROField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> USCODIGOVISITANTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> USGerenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> USMATFUNCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USMotivoBloqueioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> USSegurancaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USSenhaOpcionalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char USTIPOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USUSUARIOREDEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> USAdministrador {
            get {
                return this.USAdministradorField;
            }
            set {
                if ((this.USAdministradorField.Equals(value) != true)) {
                    this.USAdministradorField = value;
                    this.RaisePropertyChanged("USAdministrador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> USAuditor {
            get {
                return this.USAuditorField;
            }
            set {
                if ((this.USAuditorField.Equals(value) != true)) {
                    this.USAuditorField = value;
                    this.RaisePropertyChanged("USAuditor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool USBloqueado {
            get {
                return this.USBloqueadoField;
            }
            set {
                if ((this.USBloqueadoField.Equals(value) != true)) {
                    this.USBloqueadoField = value;
                    this.RaisePropertyChanged("USBloqueado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int USCODIGO {
            get {
                return this.USCODIGOField;
            }
            set {
                if ((this.USCODIGOField.Equals(value) != true)) {
                    this.USCODIGOField = value;
                    this.RaisePropertyChanged("USCODIGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> USCODIGOESTAGIARIO {
            get {
                return this.USCODIGOESTAGIARIOField;
            }
            set {
                if ((this.USCODIGOESTAGIARIOField.Equals(value) != true)) {
                    this.USCODIGOESTAGIARIOField = value;
                    this.RaisePropertyChanged("USCODIGOESTAGIARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> USCODIGOTERCEIRO {
            get {
                return this.USCODIGOTERCEIROField;
            }
            set {
                if ((this.USCODIGOTERCEIROField.Equals(value) != true)) {
                    this.USCODIGOTERCEIROField = value;
                    this.RaisePropertyChanged("USCODIGOTERCEIRO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> USCODIGOVISITANTE {
            get {
                return this.USCODIGOVISITANTEField;
            }
            set {
                if ((this.USCODIGOVISITANTEField.Equals(value) != true)) {
                    this.USCODIGOVISITANTEField = value;
                    this.RaisePropertyChanged("USCODIGOVISITANTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> USGerente {
            get {
                return this.USGerenteField;
            }
            set {
                if ((this.USGerenteField.Equals(value) != true)) {
                    this.USGerenteField = value;
                    this.RaisePropertyChanged("USGerente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> USMATFUNC {
            get {
                return this.USMATFUNCField;
            }
            set {
                if ((this.USMATFUNCField.Equals(value) != true)) {
                    this.USMATFUNCField = value;
                    this.RaisePropertyChanged("USMATFUNC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USMotivoBloqueio {
            get {
                return this.USMotivoBloqueioField;
            }
            set {
                if ((object.ReferenceEquals(this.USMotivoBloqueioField, value) != true)) {
                    this.USMotivoBloqueioField = value;
                    this.RaisePropertyChanged("USMotivoBloqueio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> USSeguranca {
            get {
                return this.USSegurancaField;
            }
            set {
                if ((this.USSegurancaField.Equals(value) != true)) {
                    this.USSegurancaField = value;
                    this.RaisePropertyChanged("USSeguranca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USSenhaOpcional {
            get {
                return this.USSenhaOpcionalField;
            }
            set {
                if ((object.ReferenceEquals(this.USSenhaOpcionalField, value) != true)) {
                    this.USSenhaOpcionalField = value;
                    this.RaisePropertyChanged("USSenhaOpcional");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char USTIPO {
            get {
                return this.USTIPOField;
            }
            set {
                if ((this.USTIPOField.Equals(value) != true)) {
                    this.USTIPOField = value;
                    this.RaisePropertyChanged("USTIPO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USUSUARIOREDE {
            get {
                return this.USUSUARIOREDEField;
            }
            set {
                if ((object.ReferenceEquals(this.USUSUARIOREDEField, value) != true)) {
                    this.USUSUARIOREDEField = value;
                    this.RaisePropertyChanged("USUSUARIOREDE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FUNCIONARIO", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class FUNCIONARIO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FUCodigoLocalidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FUCodigoLotacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FUMATFUNCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FUNOMFUNCField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FUCodigoLocalidade {
            get {
                return this.FUCodigoLocalidadeField;
            }
            set {
                if ((this.FUCodigoLocalidadeField.Equals(value) != true)) {
                    this.FUCodigoLocalidadeField = value;
                    this.RaisePropertyChanged("FUCodigoLocalidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FUCodigoLotacao {
            get {
                return this.FUCodigoLotacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.FUCodigoLotacaoField, value) != true)) {
                    this.FUCodigoLotacaoField = value;
                    this.RaisePropertyChanged("FUCodigoLotacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FUMATFUNC {
            get {
                return this.FUMATFUNCField;
            }
            set {
                if ((this.FUMATFUNCField.Equals(value) != true)) {
                    this.FUMATFUNCField = value;
                    this.RaisePropertyChanged("FUMATFUNC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FUNOMFUNC {
            get {
                return this.FUNOMFUNCField;
            }
            set {
                if ((object.ReferenceEquals(this.FUNOMFUNCField, value) != true)) {
                    this.FUNOMFUNCField = value;
                    this.RaisePropertyChanged("FUNOMFUNC");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ESTAGIARIO", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class ESTAGIARIO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ESCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ESCodigoLocalidadeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESCodigoLotacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESNomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ESCodigo {
            get {
                return this.ESCodigoField;
            }
            set {
                if ((this.ESCodigoField.Equals(value) != true)) {
                    this.ESCodigoField = value;
                    this.RaisePropertyChanged("ESCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ESCodigoLocalidade {
            get {
                return this.ESCodigoLocalidadeField;
            }
            set {
                if ((this.ESCodigoLocalidadeField.Equals(value) != true)) {
                    this.ESCodigoLocalidadeField = value;
                    this.RaisePropertyChanged("ESCodigoLocalidade");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ESCodigoLotacao {
            get {
                return this.ESCodigoLotacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.ESCodigoLotacaoField, value) != true)) {
                    this.ESCodigoLotacaoField = value;
                    this.RaisePropertyChanged("ESCodigoLotacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ESNome {
            get {
                return this.ESNomeField;
            }
            set {
                if ((object.ReferenceEquals(this.ESNomeField, value) != true)) {
                    this.ESNomeField = value;
                    this.RaisePropertyChanged("ESNome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VISITANTE", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class VISITANTE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ViCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ViNomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ViCodigo {
            get {
                return this.ViCodigoField;
            }
            set {
                if ((this.ViCodigoField.Equals(value) != true)) {
                    this.ViCodigoField = value;
                    this.RaisePropertyChanged("ViCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ViNome {
            get {
                return this.ViNomeField;
            }
            set {
                if ((object.ReferenceEquals(this.ViNomeField, value) != true)) {
                    this.ViNomeField = value;
                    this.RaisePropertyChanged("ViNome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TERCEIRO", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class TERCEIRO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TeCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeNomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TeCodigo {
            get {
                return this.TeCodigoField;
            }
            set {
                if ((this.TeCodigoField.Equals(value) != true)) {
                    this.TeCodigoField = value;
                    this.RaisePropertyChanged("TeCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeNome {
            get {
                return this.TeNomeField;
            }
            set {
                if ((object.ReferenceEquals(this.TeNomeField, value) != true)) {
                    this.TeNomeField = value;
                    this.RaisePropertyChanged("TeNome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PONTOCONTROLE", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class PONTOCONTROLE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PoBiometriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PoCartaoRFIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PoCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PoControlaSaidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PoDescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PoDisparaAlarmeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PoNomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PoObservacaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PoPermiteLiberacaoForcadaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PoSenhaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PoSmartCardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> PoTentativaIndevidaDisparaAlarmeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char PoTipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PoBiometria {
            get {
                return this.PoBiometriaField;
            }
            set {
                if ((this.PoBiometriaField.Equals(value) != true)) {
                    this.PoBiometriaField = value;
                    this.RaisePropertyChanged("PoBiometria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PoCartaoRFID {
            get {
                return this.PoCartaoRFIDField;
            }
            set {
                if ((this.PoCartaoRFIDField.Equals(value) != true)) {
                    this.PoCartaoRFIDField = value;
                    this.RaisePropertyChanged("PoCartaoRFID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PoCodigo {
            get {
                return this.PoCodigoField;
            }
            set {
                if ((this.PoCodigoField.Equals(value) != true)) {
                    this.PoCodigoField = value;
                    this.RaisePropertyChanged("PoCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PoControlaSaida {
            get {
                return this.PoControlaSaidaField;
            }
            set {
                if ((this.PoControlaSaidaField.Equals(value) != true)) {
                    this.PoControlaSaidaField = value;
                    this.RaisePropertyChanged("PoControlaSaida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PoDescricao {
            get {
                return this.PoDescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.PoDescricaoField, value) != true)) {
                    this.PoDescricaoField = value;
                    this.RaisePropertyChanged("PoDescricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PoDisparaAlarme {
            get {
                return this.PoDisparaAlarmeField;
            }
            set {
                if ((this.PoDisparaAlarmeField.Equals(value) != true)) {
                    this.PoDisparaAlarmeField = value;
                    this.RaisePropertyChanged("PoDisparaAlarme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PoNome {
            get {
                return this.PoNomeField;
            }
            set {
                if ((object.ReferenceEquals(this.PoNomeField, value) != true)) {
                    this.PoNomeField = value;
                    this.RaisePropertyChanged("PoNome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PoObservacao {
            get {
                return this.PoObservacaoField;
            }
            set {
                if ((object.ReferenceEquals(this.PoObservacaoField, value) != true)) {
                    this.PoObservacaoField = value;
                    this.RaisePropertyChanged("PoObservacao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PoPermiteLiberacaoForcada {
            get {
                return this.PoPermiteLiberacaoForcadaField;
            }
            set {
                if ((this.PoPermiteLiberacaoForcadaField.Equals(value) != true)) {
                    this.PoPermiteLiberacaoForcadaField = value;
                    this.RaisePropertyChanged("PoPermiteLiberacaoForcada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PoSenha {
            get {
                return this.PoSenhaField;
            }
            set {
                if ((this.PoSenhaField.Equals(value) != true)) {
                    this.PoSenhaField = value;
                    this.RaisePropertyChanged("PoSenha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PoSmartCard {
            get {
                return this.PoSmartCardField;
            }
            set {
                if ((this.PoSmartCardField.Equals(value) != true)) {
                    this.PoSmartCardField = value;
                    this.RaisePropertyChanged("PoSmartCard");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> PoTentativaIndevidaDisparaAlarme {
            get {
                return this.PoTentativaIndevidaDisparaAlarmeField;
            }
            set {
                if ((this.PoTentativaIndevidaDisparaAlarmeField.Equals(value) != true)) {
                    this.PoTentativaIndevidaDisparaAlarmeField = value;
                    this.RaisePropertyChanged("PoTentativaIndevidaDisparaAlarme");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char PoTipo {
            get {
                return this.PoTipoField;
            }
            set {
                if ((this.PoTipoField.Equals(value) != true)) {
                    this.PoTipoField = value;
                    this.RaisePropertyChanged("PoTipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CFiltro.ICFiltro")]
    public interface ICFiltro {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFiltro/SelecionaUsuario", ReplyAction="http://tempuri.org/ICFiltro/SelecionaUsuarioResponse")]
        ACESSO.AUDITORIA.CFiltro.USUARIO SelecionaUsuario(char Tipo, int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFiltro/SelecionaFuncionario", ReplyAction="http://tempuri.org/ICFiltro/SelecionaFuncionarioResponse")]
        ACESSO.AUDITORIA.CFiltro.FUNCIONARIO SelecionaFuncionario(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFiltro/SelecionaEstagiario", ReplyAction="http://tempuri.org/ICFiltro/SelecionaEstagiarioResponse")]
        ACESSO.AUDITORIA.CFiltro.ESTAGIARIO SelecionaEstagiario(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFiltro/SelecionaVisitante", ReplyAction="http://tempuri.org/ICFiltro/SelecionaVisitanteResponse")]
        ACESSO.AUDITORIA.CFiltro.VISITANTE SelecionaVisitante(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFiltro/SelecionaTerceiro", ReplyAction="http://tempuri.org/ICFiltro/SelecionaTerceiroResponse")]
        ACESSO.AUDITORIA.CFiltro.TERCEIRO SelecionaTerceiro(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFiltro/ListarTodosPontosControle", ReplyAction="http://tempuri.org/ICFiltro/ListarTodosPontosControleResponse")]
        ACESSO.AUDITORIA.CFiltro.PONTOCONTROLE[] ListarTodosPontosControle();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICFiltro/ListarPontosControle", ReplyAction="http://tempuri.org/ICFiltro/ListarPontosControleResponse")]
        ACESSO.AUDITORIA.CFiltro.PONTOCONTROLE[] ListarPontosControle(char Tipo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICFiltroChannel : ACESSO.AUDITORIA.CFiltro.ICFiltro, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CFiltroClient : System.ServiceModel.ClientBase<ACESSO.AUDITORIA.CFiltro.ICFiltro>, ACESSO.AUDITORIA.CFiltro.ICFiltro {
        
        public CFiltroClient() {
        }
        
        public CFiltroClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CFiltroClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CFiltroClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CFiltroClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ACESSO.AUDITORIA.CFiltro.USUARIO SelecionaUsuario(char Tipo, int Codigo) {
            return base.Channel.SelecionaUsuario(Tipo, Codigo);
        }
        
        public ACESSO.AUDITORIA.CFiltro.FUNCIONARIO SelecionaFuncionario(int Codigo) {
            return base.Channel.SelecionaFuncionario(Codigo);
        }
        
        public ACESSO.AUDITORIA.CFiltro.ESTAGIARIO SelecionaEstagiario(int Codigo) {
            return base.Channel.SelecionaEstagiario(Codigo);
        }
        
        public ACESSO.AUDITORIA.CFiltro.VISITANTE SelecionaVisitante(int Codigo) {
            return base.Channel.SelecionaVisitante(Codigo);
        }
        
        public ACESSO.AUDITORIA.CFiltro.TERCEIRO SelecionaTerceiro(int Codigo) {
            return base.Channel.SelecionaTerceiro(Codigo);
        }
        
        public ACESSO.AUDITORIA.CFiltro.PONTOCONTROLE[] ListarTodosPontosControle() {
            return base.Channel.ListarTodosPontosControle();
        }
        
        public ACESSO.AUDITORIA.CFiltro.PONTOCONTROLE[] ListarPontosControle(char Tipo) {
            return base.Channel.ListarPontosControle(Tipo);
        }
    }
}
