//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACESSO.ADMINISTRATIVO.CCartao {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CARTAO", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class CARTAO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> CrBloqueadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CrCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CrCodigoFabricanteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CrDataBloqueioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CrMotivoBloqueioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CrNumeroCartaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char CrTipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> CrBloqueado {
            get {
                return this.CrBloqueadoField;
            }
            set {
                if ((this.CrBloqueadoField.Equals(value) != true)) {
                    this.CrBloqueadoField = value;
                    this.RaisePropertyChanged("CrBloqueado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CrCodigo {
            get {
                return this.CrCodigoField;
            }
            set {
                if ((this.CrCodigoField.Equals(value) != true)) {
                    this.CrCodigoField = value;
                    this.RaisePropertyChanged("CrCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CrCodigoFabricante {
            get {
                return this.CrCodigoFabricanteField;
            }
            set {
                if ((this.CrCodigoFabricanteField.Equals(value) != true)) {
                    this.CrCodigoFabricanteField = value;
                    this.RaisePropertyChanged("CrCodigoFabricante");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CrDataBloqueio {
            get {
                return this.CrDataBloqueioField;
            }
            set {
                if ((this.CrDataBloqueioField.Equals(value) != true)) {
                    this.CrDataBloqueioField = value;
                    this.RaisePropertyChanged("CrDataBloqueio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CrMotivoBloqueio {
            get {
                return this.CrMotivoBloqueioField;
            }
            set {
                if ((object.ReferenceEquals(this.CrMotivoBloqueioField, value) != true)) {
                    this.CrMotivoBloqueioField = value;
                    this.RaisePropertyChanged("CrMotivoBloqueio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CrNumeroCartao {
            get {
                return this.CrNumeroCartaoField;
            }
            set {
                if ((object.ReferenceEquals(this.CrNumeroCartaoField, value) != true)) {
                    this.CrNumeroCartaoField = value;
                    this.RaisePropertyChanged("CrNumeroCartao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char CrTipo {
            get {
                return this.CrTipoField;
            }
            set {
                if ((this.CrTipoField.Equals(value) != true)) {
                    this.CrTipoField = value;
                    this.RaisePropertyChanged("CrTipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FABRICANTE", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class FABRICANTE : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FaCodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaNomeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FaCodigo {
            get {
                return this.FaCodigoField;
            }
            set {
                if ((this.FaCodigoField.Equals(value) != true)) {
                    this.FaCodigoField = value;
                    this.RaisePropertyChanged("FaCodigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaNome {
            get {
                return this.FaNomeField;
            }
            set {
                if ((object.ReferenceEquals(this.FaNomeField, value) != true)) {
                    this.FaNomeField = value;
                    this.RaisePropertyChanged("FaNome");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CCartao.ICCartao")]
    public interface ICCartao {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCartao/ListarCARTAOsTipo", ReplyAction="http://tempuri.org/ICCartao/ListarCARTAOsTipoResponse")]
        ACESSO.ADMINISTRATIVO.CCartao.CARTAO[] ListarCARTAOsTipo(char CodigoTipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCartao/ListarCARTAOs", ReplyAction="http://tempuri.org/ICCartao/ListarCARTAOsResponse")]
        ACESSO.ADMINISTRATIVO.CCartao.CARTAO[] ListarCARTAOs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCartao/ListarFabricantes", ReplyAction="http://tempuri.org/ICCartao/ListarFabricantesResponse")]
        ACESSO.ADMINISTRATIVO.CCartao.FABRICANTE[] ListarFabricantes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCartao/SelecionaCARTAO", ReplyAction="http://tempuri.org/ICCartao/SelecionaCARTAOResponse")]
        ACESSO.ADMINISTRATIVO.CCartao.CARTAO SelecionaCARTAO(int Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCartao/SelecionaCARTAONumero", ReplyAction="http://tempuri.org/ICCartao/SelecionaCARTAONumeroResponse")]
        ACESSO.ADMINISTRATIVO.CCartao.CARTAO[] SelecionaCARTAONumero(string Numero);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCartao/Incluir", ReplyAction="http://tempuri.org/ICCartao/IncluirResponse")]
        void Incluir(ACESSO.ADMINISTRATIVO.CCartao.CARTAO oCARTAO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCartao/Alterar", ReplyAction="http://tempuri.org/ICCartao/AlterarResponse")]
        void Alterar(ACESSO.ADMINISTRATIVO.CCartao.CARTAO oCARTAO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICCartao/Excluir", ReplyAction="http://tempuri.org/ICCartao/ExcluirResponse")]
        void Excluir(ACESSO.ADMINISTRATIVO.CCartao.CARTAO oCARTAO);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICCartaoChannel : ACESSO.ADMINISTRATIVO.CCartao.ICCartao, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CCartaoClient : System.ServiceModel.ClientBase<ACESSO.ADMINISTRATIVO.CCartao.ICCartao>, ACESSO.ADMINISTRATIVO.CCartao.ICCartao {
        
        public CCartaoClient() {
        }
        
        public CCartaoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CCartaoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CCartaoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CCartaoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ACESSO.ADMINISTRATIVO.CCartao.CARTAO[] ListarCARTAOsTipo(char CodigoTipo) {
            return base.Channel.ListarCARTAOsTipo(CodigoTipo);
        }
        
        public ACESSO.ADMINISTRATIVO.CCartao.CARTAO[] ListarCARTAOs() {
            return base.Channel.ListarCARTAOs();
        }
        
        public ACESSO.ADMINISTRATIVO.CCartao.FABRICANTE[] ListarFabricantes() {
            return base.Channel.ListarFabricantes();
        }
        
        public ACESSO.ADMINISTRATIVO.CCartao.CARTAO SelecionaCARTAO(int Codigo) {
            return base.Channel.SelecionaCARTAO(Codigo);
        }
        
        public ACESSO.ADMINISTRATIVO.CCartao.CARTAO[] SelecionaCARTAONumero(string Numero) {
            return base.Channel.SelecionaCARTAONumero(Numero);
        }
        
        public void Incluir(ACESSO.ADMINISTRATIVO.CCartao.CARTAO oCARTAO) {
            base.Channel.Incluir(oCARTAO);
        }
        
        public void Alterar(ACESSO.ADMINISTRATIVO.CCartao.CARTAO oCARTAO) {
            base.Channel.Alterar(oCARTAO);
        }
        
        public void Excluir(ACESSO.ADMINISTRATIVO.CCartao.CARTAO oCARTAO) {
            base.Channel.Excluir(oCARTAO);
        }
    }
}
