//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACESSO.AUDITORIA.CTotalAcessoPontoDia {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="vw_TotalAcessoPontoDia", Namespace="http://schemas.datacontract.org/2004/07/ACESSO.MODEL")]
    [System.SerializableAttribute()]
    public partial class vw_TotalAcessoPontoDia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ANOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int APCodigoPontoControleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool APNegadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MÊSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PoNomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char PoTipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TotalAcessoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ANO {
            get {
                return this.ANOField;
            }
            set {
                if ((this.ANOField.Equals(value) != true)) {
                    this.ANOField = value;
                    this.RaisePropertyChanged("ANO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int APCodigoPontoControle {
            get {
                return this.APCodigoPontoControleField;
            }
            set {
                if ((this.APCodigoPontoControleField.Equals(value) != true)) {
                    this.APCodigoPontoControleField = value;
                    this.RaisePropertyChanged("APCodigoPontoControle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool APNegado {
            get {
                return this.APNegadoField;
            }
            set {
                if ((this.APNegadoField.Equals(value) != true)) {
                    this.APNegadoField = value;
                    this.RaisePropertyChanged("APNegado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DIA {
            get {
                return this.DIAField;
            }
            set {
                if ((this.DIAField.Equals(value) != true)) {
                    this.DIAField = value;
                    this.RaisePropertyChanged("DIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MÊS {
            get {
                return this.MÊSField;
            }
            set {
                if ((this.MÊSField.Equals(value) != true)) {
                    this.MÊSField = value;
                    this.RaisePropertyChanged("MÊS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PoNome {
            get {
                return this.PoNomeField;
            }
            set {
                if ((object.ReferenceEquals(this.PoNomeField, value) != true)) {
                    this.PoNomeField = value;
                    this.RaisePropertyChanged("PoNome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char PoTipo {
            get {
                return this.PoTipoField;
            }
            set {
                if ((this.PoTipoField.Equals(value) != true)) {
                    this.PoTipoField = value;
                    this.RaisePropertyChanged("PoTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TotalAcesso {
            get {
                return this.TotalAcessoField;
            }
            set {
                if ((this.TotalAcessoField.Equals(value) != true)) {
                    this.TotalAcessoField = value;
                    this.RaisePropertyChanged("TotalAcesso");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CTotalAcessoPontoDia.ICTotalAcessoPontoDia")]
    public interface ICTotalAcessoPontoDia {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICTotalAcessoPontoDia/TotalAcessoPontoDia", ReplyAction="http://tempuri.org/ICTotalAcessoPontoDia/TotalAcessoPontoDiaResponse")]
        ACESSO.AUDITORIA.CTotalAcessoPontoDia.vw_TotalAcessoPontoDia[] TotalAcessoPontoDia();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICTotalAcessoPontoDia/TotalAcessoPontoDiaPeriodo", ReplyAction="http://tempuri.org/ICTotalAcessoPontoDia/TotalAcessoPontoDiaPeriodoResponse")]
        ACESSO.AUDITORIA.CTotalAcessoPontoDia.vw_TotalAcessoPontoDia[] TotalAcessoPontoDiaPeriodo(System.DateTime DataInicio, System.DateTime DataFim);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICTotalAcessoPontoDiaChannel : ACESSO.AUDITORIA.CTotalAcessoPontoDia.ICTotalAcessoPontoDia, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CTotalAcessoPontoDiaClient : System.ServiceModel.ClientBase<ACESSO.AUDITORIA.CTotalAcessoPontoDia.ICTotalAcessoPontoDia>, ACESSO.AUDITORIA.CTotalAcessoPontoDia.ICTotalAcessoPontoDia {
        
        public CTotalAcessoPontoDiaClient() {
        }
        
        public CTotalAcessoPontoDiaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CTotalAcessoPontoDiaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CTotalAcessoPontoDiaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CTotalAcessoPontoDiaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ACESSO.AUDITORIA.CTotalAcessoPontoDia.vw_TotalAcessoPontoDia[] TotalAcessoPontoDia() {
            return base.Channel.TotalAcessoPontoDia();
        }
        
        public ACESSO.AUDITORIA.CTotalAcessoPontoDia.vw_TotalAcessoPontoDia[] TotalAcessoPontoDiaPeriodo(System.DateTime DataInicio, System.DateTime DataFim) {
            return base.Channel.TotalAcessoPontoDiaPeriodo(DataInicio, DataFim);
        }
    }
}
