//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACESSO.PONTOCONTROLE.CFoto {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CFoto.IFoto")]
    public interface IFoto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFoto/DownloadFile", ReplyAction="http://tempuri.org/IFoto/DownloadFileResponse")]
        byte[] DownloadFile(string FName, int Tipo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFotoChannel : ACESSO.PONTOCONTROLE.CFoto.IFoto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FotoClient : System.ServiceModel.ClientBase<ACESSO.PONTOCONTROLE.CFoto.IFoto>, ACESSO.PONTOCONTROLE.CFoto.IFoto {
        
        public FotoClient() {
        }
        
        public FotoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FotoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FotoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FotoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public byte[] DownloadFile(string FName, int Tipo) {
            return base.Channel.DownloadFile(FName, Tipo);
        }
    }
}
