//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACESSO.PONTOCONTROLE.CAutentica {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CAutentica.ICAutentica")]
    public interface ICAutentica {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICAutentica/IsAuthenticated", ReplyAction="http://tempuri.org/ICAutentica/IsAuthenticatedResponse")]
        bool IsAuthenticated(string Domain, string UserName, string Password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICAutenticaChannel : ACESSO.PONTOCONTROLE.CAutentica.ICAutentica, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CAutenticaClient : System.ServiceModel.ClientBase<ACESSO.PONTOCONTROLE.CAutentica.ICAutentica>, ACESSO.PONTOCONTROLE.CAutentica.ICAutentica {
        
        public CAutenticaClient() {
        }
        
        public CAutenticaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CAutenticaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CAutenticaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CAutenticaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool IsAuthenticated(string Domain, string UserName, string Password) {
            return base.Channel.IsAuthenticated(Domain, UserName, Password);
        }
    }
}
